import { mkPage, text, img, qr, STOCK, P, GOLD } from './_shared';

// ── 21. Ownership Education ─────────────────────────────────────────
export const education = mkPage('ownership-education', 'Ownership Education', {
  band: text('OWNERSHIP EDUCATION', P.bandLabel),
  bandSub: text('Knowledge today. Ownership for life.', { ...P.caption, color: GOLD }),
  h1a: text('HOW TO', { ...P.displayNavy, fontSize: 34 }),
  h1b: text('BECOME AN OWNER', { ...P.displayGold, fontSize: 34 }),
  sub: text('Your guide to getting involved in racing ownership.', P.scriptGold),
  body: text('Racing ownership is more accessible than ever. Here\'s everything you need to know to get started with confidence.', P.bodySmall),
  step1: text('<b>1. Syndicates explained</b> — syndicates allow you to share the experience, costs and rewards with like-minded people.', P.bodySmall),
  step2: text('<b>2. Costs involved</b> — upfront costs vary, but ownership can be more affordable than you think.', P.bodySmall),
  step3: text('<b>3. Choosing the right trainer</b> — a great trainer is key to your horse\'s success and your enjoyment.', P.bodySmall),
  step4: text('<b>4. Ownership etiquette</b> — good manners and respect make racing enjoyable for everyone.', P.bodySmall),
  step5: text('<b>5. The experience</b> — from mornings at the stables to race-day thrills, it\'s a journey you\'ll never forget.', P.bodySmall),
  photoStrip: img(STOCK.crowd, 'cover'),
  toolsTitle: text('USEFUL TOOLS TO GET STARTED', { ...P.kickerGold, fontSize: 9 }),
  tool1: text('Ownership calculator — estimate costs and plan your ownership journey.', P.bodySmall),
  tool1Qr: qr('https://nztrof.co.nz/calculator'),
  tool2: text('Trainer directory — search trainers by location and specialty.', P.bodySmall),
  tool2Qr: qr('https://nztrof.co.nz/trainers'),
  tool3: text('Syndicate finder — find the right syndicate for you.', P.bodySmall),
  tool3Qr: qr('https://nztrof.co.nz/syndicates'),
  ctaTitle: text('LEARN. CONNECT. EXPERIENCE.', P.kickerNavy),
  ctaBody: text('Join stable visits, information evenings and ownership events across New Zealand. We\'re here to help you every step of the way.', P.bodySmall),
  guideQr: qr('https://nztrof.co.nz/starter-guide'),
  guideNote: text('NEW TO RACING? Scan to access our complete Ownership Starter Guide.', P.qrLabel),
  footer: text('OWNERSHIP IS MORE THAN A HORSE. IT\'S A COMMUNITY. WE CAN\'T WAIT TO WELCOME YOU.', P.footer),
  pageNum: text('PAGE 17', { ...P.footer, align: 'right' }),
});
