import { mkPage, text, img, qr, STOCK, P, GOLD } from './_shared';

// ── 5. Best Headline Story — Aeliana ────────────────────────────────
export const headline = mkPage('headline-story', 'Headline Story — Aeliana', {
  band: text('BEST HEADLINE STORY', P.bandLabel),
  bandSub: text('Extraordinary stories. Real people. Real impact.', { ...P.caption, color: GOLD }),
  title: text('AELIANA', { ...P.displayNavy, fontSize: 52, letterSpacing: 1 }),
  subtitle: text('THE HOMEGROWN STAR<br>WHO TOOK THE WORLD BY STORM', { ...P.headlineGold, fontSize: 18 }),
  hero: img(STOCK.jockeyRace, 'cover'),
  intro: text('From a Waikato farm to the world stage — Aeliana\'s story is the stuff of dreams. Bred by John Thompson and the team at Richill Farm, Aeliana was sold at the 2020 New Zealand Bloodstock Karaka Yearling Sale for NZ$210,000. What followed was nothing short of phenomenal.', P.body),
  stat1Num: text('NZ$210,000', P.statBig),
  stat1Label: text('SOLD AT KARAKA 2020 · BY RICHILL FARM', P.statLabel),
  stat2Num: text('A$4.24M+', P.statBig),
  stat2Label: text('CAREER EARNINGS (AND COUNTING)', P.statLabel),
  stat3Num: text('6', P.statBig),
  stat3Label: text('GROUP 1 WINS IN AUSTRALIA', P.statLabel),
  stat4Num: text('★', P.statBig),
  stat4Label: text('A STAR ON THE WORLD STAGE', P.statLabel),
  journeyTitle: text('THE JOURNEY', { ...P.kickerGold, fontSize: 11 }),
  j1: text('<b>Bred with vision</b> — John Thompson\'s commitment to breeding quality at Richill Farm produced a filly with all the right ingredients.', P.bodySmall),
  j2: text('<b>Karaka moment</b> — offered by Richill Farm at Karaka 2020 and purchased for NZ$210,000.', P.bodySmall),
  j3: text('<b>Rising star</b> — trained by Ciaron Maher, Aeliana showed talent early, quickly rising through the grades.', P.bodySmall),
  j4: text('<b>Group 1 glory</b> — winner of the Australian Oaks, The Tancred Stakes, The Thousand Guineas and more.', P.bodySmall),
  j5: text('<b>An inspiration</b> — a powerful reminder of what great breeding, patience and passion can achieve.', P.bodySmall),
  photo1: img(STOCK.winnersCircle, 'cover'),
  photo2: img(STOCK.raceFinish, 'cover'),
  quote: text('It\'s every breeder\'s dream to breed a Group 1 winner — to do it on the world stage is beyond words.', P.pullQuote),
  quoteBy: text('— John Thompson, Richill Farm', P.role),
  exploreTitle: text('EXPLORE THE AELIANA STORY', { ...P.bandLabel, fontSize: 11 }),
  qr1: qr('https://nztrof.co.nz/aeliana/replays'),
  qr1Label: text('RACE REPLAYS', P.qrLabel),
  qr2: qr('https://nztrof.co.nz/aeliana/record'),
  qr2Label: text('FULL RACE RECORD', P.qrLabel),
  qr3: qr('https://nztrof.co.nz/aeliana/interviews'),
  qr3Label: text('OWNER &amp; BREEDER INTERVIEWS', P.qrLabel),
  qr4: qr('https://nztrof.co.nz/aeliana/breeding'),
  qr4Label: text('NZ BREEDING SUCCESS', P.qrLabel),
  qr5: qr('https://nztrof.co.nz/ownership'),
  qr5Label: text('OWNERSHIP OPPORTUNITIES', P.qrLabel),
  footer: text('GREAT HORSES. GREAT PEOPLE. GREAT STORIES.', P.footer),
  pageNum: text('PAGE 27', { ...P.footer, align: 'right' }),
});
