import { mkPage, text, img, qr, winnerCard, STOCK, P, GOLD } from './_shared';

// ── 22. Winning Moments ─────────────────────────────────────────────
export const winning = mkPage('winning-moments', 'Winning Moments', {
  band: text('WINNING MOMENTS  🏆', P.bandLabel),
  bandSub: text('The thrill. The people. The pride.', { ...P.caption, color: GOLD }),
  h1a: text('OWNERSHIP. PASSION.', { ...P.displayNavy, fontSize: 30 }),
  h1b: text('VICTORY.', { ...P.displayGold, fontSize: 30 }),
  sub: text('Moments that stay with you forever.', P.scriptGold),
  intro: text('Congratulations to all our winning connections from the past month.', P.bodySmall),
  heroImg: img(STOCK.ownersCelebrate, 'cover'),
  ...winnerCard('w1', STOCK.winnersCircle, 'GROUP 1 VICTORY — SISTEMA STAKES', 'IMPERIAL GIFT', 'Owners: Paddock Partners Syndicate (Mgr: D. Anderson). Trainer: M. Walker · Jockey: M. Cartwright'),
  ...winnerCard('w2', STOCK.raceFinish, 'GROUP 2 VICTORY — AVONDALE GUINEAS', 'VOYAGE BUBBLE', 'Owners: Bubble Racing Syndicate (Mgr: Mrs L. Latta). Trainer: T. Pike · Jockey: O. Bosson'),
  ...winnerCard('w3', STOCK.jockeyRace, 'GROUP 3 VICTORY — WAIKATO GUINEAS', 'SAVABEEL', 'Owners: Savannah Success Syndicate. Trainer: M. Walker · Jockey: J. McDonald'),
  ...winnerCard('w4', STOCK.celebrate2, 'LISTED — COUPLAND\'S MILE', 'MISS TIVACI', 'Owners: Tivaci Girls Syndicate (Mgr: K. Fursdon). Trainer: S & E. Clotworthy · Jockey: M. Coleman'),
  ...winnerCard('w5', STOCK.crowd2, 'BENCHMARK WINNER — MATAMATA', 'OCEAN EMPRESS', 'Owners: Blue Ocean Racing (Mgr: B. Hargreaves). Trainer: S. Marsh · Jockey: W. Pinn'),
  uploadQr: qr('https://nztrof.co.nz/upload'),
  uploadNote: text('Share your winning moments with the ownership community! Upload your photos online now.', P.qrLabel),
  footer: text('EVERY WINNER HAS A TEAM BEHIND THEM.', P.footer),
  pageNum: text('PAGE 18', { ...P.footer, align: 'right' }),
});

// ── 23. Owners Voice ────────────────────────────────────────────────
export const voice = mkPage('owners-voice', 'Community & Contentious Issues', {
  band: text('COMMUNITY & CONTENTIOUS ISSUES  💬', P.bandLabel),
  bandSub: text('Stronger together. Better racing.', { ...P.caption, color: GOLD }),
  h1a: text('THE OWNERS\'', { ...P.displayNavy, fontSize: 34 }),
  h1b: text('VOICE', { ...P.displayGold, fontSize: 34 }),
  sub: text('Your experiences. Your ideas. Our future.', P.scriptGold),
  intro: text('Racing thrives when owners feel heard. This section is your platform to share feedback, raise concerns and suggest improvements that will help shape a stronger, more rewarding ownership experience for everyone.', P.bodySmall),
  col1Title: text('OWNERSHIP EXPERIENCES', P.kickerNavy),
  col1Said: text('<b>What you said:</b> Some owners feel disconnected after joining; information can be hard to find.', P.bodySmall),
  col1Ideas: text('<b>Ideas for change:</b> Better onboarding for new owners; a centralised communication hub.', P.bodySmall),
  col2Title: text('RACEDAY TREATMENT', P.kickerNavy),
  col2Said: text('<b>What you said:</b> Access and recognition can be inconsistent; facilities vary by venue.', P.bodySmall),
  col2Ideas: text('<b>Ideas for change:</b> Consistent owner recognition across all venues; more owners\' bars.', P.bodySmall),
  col3Title: text('COMMUNICATION IMPROVEMENTS', P.kickerNavy),
  col3Said: text('<b>What you said:</b> Race information isn\'t always easy to access; updates can be slow.', P.bodySmall),
  col3Ideas: text('<b>Ideas for change:</b> Real-time updates via app and SMS; regular newsletters and video updates.', P.bodySmall),
  col4Title: text('SUGGESTIONS FOR CHANGE', P.kickerNavy),
  col4Said: text('<b>What you said:</b> More opportunities to engage with trainers; desire for affordable options.', P.bodySmall),
  col4Ideas: text('<b>Ideas for change:</b> More stable visits and owner events; growth of micro-share ownership.', P.bodySmall),
  buildTitle: text('LET\'S BUILD A BETTER FUTURE', P.kickerGold),
  buildBody: text('Your feedback helps drive meaningful change. Together, we can create a racing industry that listens, learns and leads. Stronger owners. Stronger racing.', P.bodySmall),
  boardImg: img(STOCK.crowd, 'cover'),
  sayQr: qr('https://nztrof.co.nz/have-your-say'),
  sayNote: text('HAVE YOUR SAY — scan to submit your views and help shape the future of racing ownership.', P.qrLabel),
  topics: text('RECENT TOPICS RAISED BY OWNERS — More transparency around stake distribution · Improved access to race replays · More mid-week raceday experiences · Continued focus on horse welfare · More affordable ways to get involved', { ...P.kickerNavy, fontSize: 8.5 }),
  footer: text('YOUR VOICE. YOUR COMMUNITY. YOUR RACING. TOGETHER, WE CAN MAKE A DIFFERENCE.', P.footer),
  pageNum: text('PAGE 19', { ...P.footer, align: 'right' }),
});
