import { mkPage, text, img, qr, STOCK, P } from './_shared';

// ── 6. Young Owners ─────────────────────────────────────────────────
export const young = mkPage('young-owners', 'Young Owners Feature', {
  band: text('YOUNG OWNERS FEATURE', P.bandLabel),
  h1a: text('THE NEXT', { ...P.displayNavy, fontSize: 34 }),
  h1b: text('GENERATION', { ...P.displayGold, fontSize: 34 }),
  h1c: text('OF RACING', { ...P.displayNavy, fontSize: 34 }),
  sub: text('Passion today. Legacy tomorrow.', P.scriptGold),
  body: text('Racing has always been about community, courage and the thrill of chasing dreams. Today, a new generation of young owners and industry participants is stepping forward — bringing fresh ideas, big ambitions and an unstoppable love for the sport.', P.body),
  hero: img(STOCK.crowd, 'cover'),
  quote: text('It\'s more than owning a horse. It\'s being part of something bigger than yourself.', P.pullQuoteWhite),
  charlieTitle: text('MEET CHARLIE KING', P.kickerGold),
  charlieImg: img(STOCK.portrait1, 'cover'),
  charlieBody: text('From the green hills of Cambridge to the blueblood corridors of Kentucky, Charlie King is carving his own path. With a deep respect for tradition and an eye on the future, Charlie is passionate about building a life in racing.', P.bodySmall),
  charlieQuote: text('"Racing has given me opportunities, mentors and a future I wouldn\'t trade for anything." — Charlie King', P.caption),
  charlieQr: qr('https://nztrof.co.nz/charlie-king'),
  waveTitle: text('THE NEXT WAVE', { ...P.kickerWhite, fontSize: 9 }),
  waveBody: text('• Younger syndicate members bringing energy and ideas<br>• Friends turning into partners in the journey<br>• New voices shaping the future of our sport', { ...P.bodySmall, color: '#dfe6f2' }),
  pathTitle: text('PATHWAYS INTO OWNERSHIP', P.kickerNavy),
  path1: text('<b>Get started</b> — start small, learn the ropes and surround yourself with great people.', P.bodySmall),
  path2: text('<b>Be part of a team</b> — syndicates make ownership accessible, affordable and unforgettable.', P.bodySmall),
  path3: text('<b>Build your knowledge</b> — ask questions, visit stables, attend sales and soak up every experience.', P.bodySmall),
  guideQr: qr('https://nztrof.co.nz/starter-guide'),
  guideNote: text('YOUNG OWNERS STARTER GUIDE', P.qrLabel),
  col1Title: text('BALANCING WORK AND RACING', P.kickerNavy),
  col1Body: text('From early mornings to long hours, young owners are finding ways to chase their dreams while building their careers. Balance is the key to a sustainable passion.', P.bodySmall),
  col2Title: text('SOCIAL RACING CULTURE', P.kickerNavy),
  col2Body: text('Racing brings people together. New friendships, shared celebrations and memories that last a lifetime. The social side of racing is what keeps us coming back.', P.bodySmall),
  footer: text('OWNERSHIP. OPPORTUNITY. COMMUNITY.', P.footer),
  pageNum: text('PAGE 4', { ...P.footer, align: 'left' }),
});

// ── 7. Women in Racing ──────────────────────────────────────────────
export const women = mkPage('women-in-racing', 'Women in Racing', {
  band: text('WOMEN IN RACING', { ...P.bandLabel }),
  h1a: text('STYLE.', { ...P.displayNavy, fontSize: 38 }),
  h1b: text('PASSION.', { ...P.displayNavy, fontSize: 38, color: '#7a1f2b' }),
  h1c: text('LEADERSHIP.', { ...P.displayNavy, fontSize: 38, color: '#7a1f2b' }),
  sub: text('Women powering the future of racing.', P.scriptGold),
  body: text('From the winner\'s circle to the boardroom, women are leading, inspiring and making their mark on every part of our great sport.', P.body),
  collage1: img(STOCK.women, 'cover'),
  collage2: img(STOCK.champagne, 'cover'),
  collage3: img(STOCK.crowd, 'cover'),
  col1Title: text('OWNERSHIP GROUPS', P.kickerNavy),
  col1Body: text('Strong women. Shared dreams. Lasting friendships. Together we celebrate every moment.', P.bodySmall),
  col2Title: text('FEMALE BUSINESS LEADERS', P.kickerNavy),
  col2Body: text('Balancing business, family and a passion for racing. Women leading in and beyond the industry.', P.bodySmall),
  col3Title: text('RACE-DAY STYLE', P.kickerNavy),
  col3Body: text('Elegance, colour and confidence. Our race days are a celebration of fashion and fun.', P.bodySmall),
  sponsorKicker: text('LUXURY PARTNER SPOTLIGHT', P.kickerGold),
  sponsorScript: text('Experience the finest', P.script),
  sponsorBody: text('Proudly supporting women in racing and celebrating excellence in style, passion and performance.', P.bodySmall),
  sponsorName: text('ELLERSLIE LANE — NEW ZEALAND', { ...P.kickerNavy, fontSize: 11 }),
  sponsorImg: img(STOCK.women, 'cover'),
  sponsorTag: text('Timeless elegance. Racing is more than a sport, it\'s a lifestyle. ellerslielane.co.nz', P.caption),
  voteQr: qr('https://nztrof.co.nz/raceday-style-vote'),
  voteNote: text('VOTE FOR YOUR FAVOURITE RACE-DAY STYLE', P.qrLabel),
  footer: text('WOMEN. INFLUENCE. INSPIRATION.', P.footer),
  pageNum: text('PAGE 5', { ...P.footer, align: 'right' }),
});
