// ---------------------------------------------------------------------------
// The scalar types everything else is built from.
//
// This file, and this package, import nothing (FOUNDATION v0.3 §4). Every other
// package depends on mb-schema, so a dependency here is a dependency everywhere.
// ---------------------------------------------------------------------------

/**
 * Pixels in the page's own canonical space. A4 at 150 DPI is 1240 x 1754.
 *
 * The document is pixels throughout and the user never sees them — the UI
 * converts to millimetres and points at its boundary (see ./units). ADR-002.
 */
export type Px = number;

/**
 * A nanoid(12), URL-safe.
 *
 * Generation is the caller's job: this package imports nothing, so factories
 * take an id generator rather than reaching for one.
 */
export type Id = string;

/**
 * A fractional index from the `fractional-indexing` package, which sorts
 * lexicographically.
 *
 * Ordered collections carry one of these per member and are stored sorted by
 * it. Keys are GENERATED by command handlers in mb-commands, never here —
 * placing an item between two neighbours is a write, and writes are commands.
 */
export type OrderKey = string;

/** A box in page-canonical pixels. Origin is the page's top-left. */
export interface Rect {
  x: Px;
  y: Px;
  w: Px;
  h: Px;
}

/** Edge offsets in page-canonical pixels. */
export interface Insets {
  top: Px;
  right: Px;
  bottom: Px;
  left: Px;
}

/**
 * An RGB hex colour, `#rrggbb` or `#rrggbbaa`.
 *
 * Screen-first, so there is no CMYK and no spot colour. Deliberately a plain
 * alias rather than a branded type: a brand would need a cast at every lane
 * boundary, and would be a lie about values arriving as JSON off the wire.
 */
export type Color = string;
