/**
 * In-memory mock database for Stable Press.
 * Populated with rich dummy data for all entities.
 * Mutated by the mock API handler so store actions work end-to-end.
 */

import type { Article } from '@/types/article';
import type { Horse } from '@/types/horse';
import type { Party } from '@/types/party';
import type { Race, Tip } from '@/types/tip';
import type { PodcastEpisode } from '@/types/podcast';
import type { HorsePartyLink } from '@/types/horsePartyLink';
import type { MediaItem } from '@/types/mediaItem';
import type { RacingEntry } from '@/types/racingEntry';
import type { Sale } from '@/types/sale';
import type { HorseReport } from '@/types/horseReport';
import { SEED_HORSES, SEED_PARTIES_ALL } from '@/lib/seedAll';

// ─── Counter for ID generation ───────────────────────────────────────────────
let _seq = 1000;
export function nextId(prefix: string) {
  return `${prefix}-${++_seq}`;
}

// ─── Articles ─────────────────────────────────────────────────────────────────
export const articles: Article[] = [
  // ── Race Reports ──
  {
    id: 'art-001',
    title: "Savile Row Lights Up Flemington in Stunning Cox Plate Prep",
    summary:
      "The Ciaron Maher-trained Savile Row demolished a quality field at Flemington on Saturday, clocking the fastest sectionals seen at the track this preparation. A Cox Plate tilt is now firmly on the agenda.",
    author: 'Patrick Gillespie',
    status: 'published',
    category: 'Race Report',
    imageUrl: 'https://images.pexels.com/photos/1996333/pexels-photo-1996333.jpeg',
    linkedHorseIds: ['seed-savile-row-001'],
    tags: ['flemington', 'cox plate', 'group 1'],
    readingTime: 4,
    publishedAt: new Date('2025-09-12T08:00:00Z'),
    createdAt: new Date('2025-09-11T14:22:00Z'),
  },
  {
    id: 'art-009',
    title: "Iron Monarch Claims Moonee Valley Night Crown",
    summary:
      "A dominant front-running display from Iron Monarch at Moonee Valley under lights gave connections exactly what they needed ahead of the Cox Plate series. Craig Williams rode a perfectly judged race, slipping through on the rail at the 800m and never looking likely to be beaten.",
    author: 'Patrick Gillespie',
    status: 'published',
    category: 'Race Report',
    imageUrl: 'https://images.pexels.com/photos/1995842/pexels-photo-1995842.jpeg',
    linkedHorseIds: ['seed-iron-monarch-001'],
    tags: ['moonee valley', 'night racing', 'cox plate prep'],
    readingTime: 3,
    publishedAt: new Date('2025-09-06T22:30:00Z'),
    createdAt: new Date('2025-09-06T23:00:00Z'),
  },
  {
    id: 'art-013',
    title: "Desert Queen Crushes the Autumn Final Field",
    summary:
      "John O'Shea's Desert Queen produced one of the performances of the season with a dominant five-length win at Randwick. Rating the run on the clock, she recorded a figure that puts her in Group 1 company without question.",
    author: 'Eleanor Hartley',
    status: 'published',
    category: 'Race Report',
    imageUrl: 'https://images.pexels.com/photos/1571939/pexels-photo-1571939.jpeg',
    linkedHorseIds: ['seed-desert-queen-001'],
    tags: ['randwick', 'race report', 'group 1'],
    readingTime: 3,
    publishedAt: new Date('2025-09-18T10:00:00Z'),
    createdAt: new Date('2025-09-18T08:30:00Z'),
  },
  {
    id: 'art-014',
    title: "Caulfield Cup Race Day: Atmosphere, Form and Final Verdict",
    summary:
      "Twelve thousand racegoers packed Caulfield as an international field of eighteen lined up for the $5 million feature. We covered the full card, tracked the market moves, and emerged with a clear picture of where the spring heads next.",
    author: 'Stephanie Voss',
    status: 'published',
    category: 'Race Report',
    imageUrl: 'https://images.pexels.com/photos/1128428/pexels-photo-1128428.jpeg',
    linkedHorseIds: [],
    tags: ['caulfield cup', 'spring carnival', 'race day'],
    readingTime: 5,
    publishedAt: new Date('2025-09-20T18:00:00Z'),
    createdAt: new Date('2025-09-20T17:00:00Z'),
  },

  // ── Features ──
  {
    id: 'art-002',
    title: "The Spring Carnival Blueprint: Five Horses to Follow",
    summary:
      "Our editorial team breaks down the five thoroughbreds that carry the most interest heading into Melbourne's showpiece spring carnival. Form, market, and pedigree dissected.",
    author: 'Eleanor Hartley',
    status: 'published',
    category: 'Feature',
    imageUrl: 'https://images.pexels.com/photos/635499/pexels-photo-635499.jpeg',
    linkedHorseIds: ['seed-savile-row-001', 'seed-northern-star-001', 'seed-desert-queen-001'],
    tags: ['spring carnival', 'melbourne cup', 'analysis'],
    readingTime: 7,
    publishedAt: new Date('2025-09-08T07:30:00Z'),
    createdAt: new Date('2025-09-07T16:00:00Z'),
  },
  {
    id: 'art-006',
    title: "The Quiet Genius of Ciaron Maher: A Training Master Profile",
    summary:
      "Behind the championship premiership tallies lies a relentless obsession with craft. We spend a morning at Caulfield to understand what makes the master trainer tick.",
    author: 'Eleanor Hartley',
    status: 'published',
    category: 'Feature',
    imageUrl: 'https://images.pexels.com/photos/1639729/pexels-photo-1639729.jpeg',
    linkedHorseIds: ['seed-savile-row-001'],
    tags: ['trainer', 'profile', 'caulfield', 'behind the scenes'],
    readingTime: 9,
    publishedAt: new Date('2025-09-01T08:00:00Z'),
    createdAt: new Date('2025-08-30T14:00:00Z'),
  },
  {
    id: 'art-012',
    title: "The Art of the Syndicate: Inside Porter Pelchen Bloodstock",
    summary:
      "Few agencies have placed more horses in Melbourne's top paddocks this decade than Porter Pelchen Bloodstock. We go behind the scenes of Australia's most active purchasing operation.",
    author: 'James Alcott',
    status: 'published',
    category: 'Feature',
    imageUrl: 'https://images.pexels.com/photos/2291264/pexels-photo-2291264.jpeg',
    linkedHorseIds: ['seed-savile-row-001'],
    tags: ['bloodstock', 'syndicate', 'yearling sales'],
    readingTime: 8,
    publishedAt: new Date('2025-08-15T08:00:00Z'),
    createdAt: new Date('2025-08-14T16:00:00Z'),
  },
  {
    id: 'art-015',
    title: "Queensland in Autumn: The Carnival That Rewards the Patient",
    summary:
      "While Sydney and Melbourne dominate the narrative, the Sunshine State continues to produce a program that rewards proper horsemanship and patience. We trace the full Queensland autumn carnival circuit.",
    author: 'James Alcott',
    status: 'published',
    category: 'Feature',
    imageUrl: 'https://images.pexels.com/photos/3280908/pexels-photo-3280908.jpeg',
    linkedHorseIds: ['seed-northern-star-001'],
    tags: ['queensland', 'autumn carnival', 'feature'],
    readingTime: 10,
    publishedAt: new Date('2025-08-10T07:00:00Z'),
    createdAt: new Date('2025-08-09T15:00:00Z'),
  },

  // ── Spotlights ──
  {
    id: 'art-003',
    title: "Northern Star Chases Brisbane Glory After Stunning Winter Campaign",
    summary:
      "Two wins from two starts this winter have elevated Northern Star to genuine Queensland classic contender status. Trainer Ron Hutchings believes he has never had a horse with this kind of raw ability.",
    author: 'James Alcott',
    status: 'published',
    category: 'Spotlight',
    imageUrl: 'https://images.pexels.com/photos/635499/pexels-photo-635499.jpeg',
    linkedHorseIds: ['seed-northern-star-001'],
    tags: ['brisbane', 'winter carnival', 'queensland'],
    readingTime: 5,
    publishedAt: new Date('2025-08-28T09:00:00Z'),
    createdAt: new Date('2025-08-27T12:15:00Z'),
  },

  // ── Profiles ──
  {
    id: 'art-004',
    title: "Desert Queen: The Mare Taking On the Boys",
    summary:
      "It is rare to see a mare compete at the highest level in open company this early in her career. Desert Queen is doing exactly that — and winning. We profile the horse rewriting the record books.",
    author: 'Stephanie Voss',
    status: 'published',
    category: 'Profile',
    imageUrl: 'https://images.pexels.com/photos/1571939/pexels-photo-1571939.jpeg',
    linkedHorseIds: ['seed-desert-queen-001'],
    tags: ['mare', 'open company', 'profile'],
    readingTime: 6,
    publishedAt: new Date('2025-09-03T10:00:00Z'),
    createdAt: new Date('2025-09-02T09:45:00Z'),
  },
  {
    id: 'art-011',
    title: "Silk Road to Stardom: How Damian Hogan Became Racing's Most Sought Jockey",
    summary:
      "At just 26, Damian Hogan rides more Group 1 horses than any other Australian jockey. We trace the journey from Bendigo barrier trials to Flemington straight glory.",
    author: 'Stephanie Voss',
    status: 'submitted',
    category: 'Profile',
    imageUrl: 'https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg',
    linkedHorseIds: ['seed-savile-row-001'],
    tags: ['jockey', 'damian hogan', 'profile'],
    readingTime: 7,
    publishedAt: null,
    createdAt: new Date('2025-09-14T11:30:00Z'),
  },
  {
    id: 'art-016',
    title: "Iron Monarch at 24: The Gelding Who Refuses to Quit",
    summary:
      "Career start number 24 came and went with another front-running display at Moonee Valley. Iron Monarch's trainer Charlie Whitfield has trained hundreds of horses — but none quite like this.",
    author: 'Patrick Gillespie',
    status: 'published',
    category: 'Profile',
    imageUrl: 'https://images.pexels.com/photos/1995842/pexels-photo-1995842.jpeg',
    linkedHorseIds: ['seed-iron-monarch-001'],
    tags: ['iron monarch', 'profile', 'gelding'],
    readingTime: 6,
    publishedAt: new Date('2025-09-09T08:00:00Z'),
    createdAt: new Date('2025-09-08T16:00:00Z'),
  },

  // ── Previews ──
  {
    id: 'art-005',
    title: "Caulfield Preview: Irish Raider Headlines Star-Studded Field",
    summary:
      "A Group 2 at Caulfield this Saturday draws an international entry and five local Group 1 winners. We assess the market and map out the likely pace scenario.",
    author: 'Patrick Gillespie',
    status: 'published',
    category: 'Preview',
    imageUrl: 'https://images.pexels.com/photos/1128428/pexels-photo-1128428.jpeg',
    linkedHorseIds: [],
    tags: ['caulfield', 'preview', 'group 2', 'international'],
    readingTime: 5,
    publishedAt: new Date('2025-09-15T06:00:00Z'),
    createdAt: new Date('2025-09-14T18:30:00Z'),
  },
  {
    id: 'art-017',
    title: "Melbourne Cup Field: The Complete Pre-Race Dossier",
    summary:
      "With barrier draw complete and markets settled, we publish our annual race-by-runner breakdown. Every starter assessed: best case scenario, worst case risk, and one figure that tells the story.",
    author: 'Eleanor Hartley',
    status: 'published',
    category: 'Preview',
    imageUrl: 'https://images.pexels.com/photos/1996333/pexels-photo-1996333.jpeg',
    linkedHorseIds: ['seed-northern-star-001'],
    tags: ['melbourne cup', 'preview', 'form guide'],
    readingTime: 12,
    publishedAt: new Date('2025-09-21T06:30:00Z'),
    createdAt: new Date('2025-09-20T20:00:00Z'),
  },

  // ── Analysis ──
  {
    id: 'art-007',
    title: "Pedigree Deep Dive: The Dubawi Influence on Australian Racing",
    summary:
      "Dubawi-line horses have quietly dominated Group 1 racing in Australia over the past three seasons. We chart the bloodline's rise, identify the key producers, and name the next generation to watch.",
    author: 'Stephanie Voss',
    status: 'published',
    category: 'Analysis',
    imageUrl: 'https://images.pexels.com/photos/2123375/pexels-photo-2123375.jpeg',
    linkedHorseIds: ['seed-savile-row-001'],
    tags: ['pedigree', 'dubawi', 'bloodlines', 'analysis'],
    readingTime: 8,
    publishedAt: new Date('2025-08-20T07:00:00Z'),
    createdAt: new Date('2025-08-19T13:00:00Z'),
  },
  {
    id: 'art-018',
    title: "Track Bias Report: Flemington Spring Preparation Wrap",
    summary:
      "Eight weeks of meetings, four different configurations, and one consistent theme: horses drawn wide have struggled at the 1200m and 1400m. Our sectional analyst maps the bias with precision and explains what it means for Group 1 day.",
    author: 'James Alcott',
    status: 'published',
    category: 'Analysis',
    imageUrl: 'https://images.pexels.com/photos/2123375/pexels-photo-2123375.jpeg',
    linkedHorseIds: [],
    tags: ['flemington', 'track bias', 'sectionals', 'analysis'],
    readingTime: 7,
    publishedAt: new Date('2025-09-22T07:00:00Z'),
    createdAt: new Date('2025-09-21T18:00:00Z'),
  },
  {
    id: 'art-019',
    title: "Speed Maps and Pace Scenarios: The Cox Plate Blueprint",
    summary:
      "Who leads? Who rolls forward? Who sits and covers? This is the most detailed pace analysis published ahead of the Cox Plate. We model three scenarios and name the horse who benefits most from each.",
    author: 'Stephanie Voss',
    status: 'published',
    category: 'Analysis',
    imageUrl: 'https://images.pexels.com/photos/27305774/pexels-photo-27305774.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    linkedHorseIds: ['seed-savile-row-001', 'seed-iron-monarch-001'],
    tags: ['cox plate', 'pace analysis', 'speed map'],
    readingTime: 9,
    publishedAt: new Date('2025-09-16T07:00:00Z'),
    createdAt: new Date('2025-09-15T20:00:00Z'),
  },
  {
    id: 'art-010',
    title: "Two-Year-Old Watch: The Juveniles to Follow This Spring",
    summary:
      "Our bloodstock analyst has singled out six two-year-olds from the barrier trials with the profile to develop into serious classic horses. Meet the next generation of champions.",
    author: 'Eleanor Hartley',
    status: 'draft',
    category: 'Analysis',
    imageUrl: 'https://images.pexels.com/photos/3280908/pexels-photo-3280908.jpeg',
    linkedHorseIds: [],
    tags: ['juveniles', 'two-year-olds', 'classics', 'barrier trials'],
    readingTime: 6,
    publishedAt: null,
    createdAt: new Date('2025-09-17T10:00:00Z'),
  },

  // ── Newsroom drafts / in-progress ──
  {
    id: 'art-008',
    title: "Road to the Melbourne Cup: Form Guide and Market Moves",
    summary:
      "With nominations closing this week, the betting market is already shifting. We track the key runners, their preferred conditions, and where the value currently sits.",
    author: 'James Alcott',
    status: 'editorial_review',
    category: 'Preview',
    imageUrl: 'https://images.pexels.com/photos/1181346/pexels-photo-1181346.jpeg',
    linkedHorseIds: [],
    tags: ['melbourne cup', 'form guide', 'market'],
    readingTime: 6,
    publishedAt: null,
    createdAt: new Date('2025-09-16T09:00:00Z'),
  },
  {
    id: 'art-020',
    title: "James McDonald: The Thinking Jockey's Thinking Jockey",
    summary:
      "He rarely says the obvious thing. He almost never wins ugly. We sit with James McDonald for an hour and explore what separates a champion from a champion-level rider.",
    author: 'Eleanor Hartley',
    status: 'submitted',
    category: 'Profile',
    imageUrl: 'https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg',
    linkedHorseIds: ['seed-northern-star-001'],
    tags: ['james mcdonald', 'jockey', 'interview'],
    readingTime: 8,
    publishedAt: null,
    createdAt: new Date('2025-09-19T11:00:00Z'),
  },
  {
    id: 'art-021',
    title: "Owner's Diary: Twelve Months with Desert Queen",
    summary:
      "Katherine Dunmore kept a private diary from the moment she signed the sales slip. Now, with Desert Queen rated 118, she shares it for the first time — unedited.",
    author: 'Patrick Gillespie',
    status: 'published',
    category: 'Feature',
    imageUrl: 'https://images.pexels.com/photos/1571939/pexels-photo-1571939.jpeg',
    linkedHorseIds: ['seed-desert-queen-001'],
    tags: ['owner', 'desert queen', 'behind the scenes'],
    readingTime: 11,
    publishedAt: new Date('2025-09-23T08:00:00Z'),
    createdAt: new Date('2025-09-22T14:00:00Z'),
  },
  {
    id: 'art-022',
    title: "Morning Line: Randwick Saturday Card Previews",
    summary:
      "Seven races, forty-three starters, and a near-perfect early spring day forecast. Our morning preview covers every race on the Randwick Saturday card with selections, form picks, and the one runner to watch in each field.",
    author: 'Stephanie Voss',
    status: 'published',
    category: 'Preview',
    imageUrl: 'https://images.pexels.com/photos/12995066/pexels-photo-12995066.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    linkedHorseIds: [],
    tags: ['randwick', 'saturday card', 'morning preview'],
    readingTime: 5,
    publishedAt: new Date('2025-09-24T06:00:00Z'),
    createdAt: new Date('2025-09-23T22:00:00Z'),
  },
  {
    id: 'art-023',
    title: "The Science of the Barrier Trial: Why It Matters More Than You Think",
    summary:
      "Trainers use barrier trials to tell the public nothing — and sometimes everything. Our form analyst spent twelve months tracking the correlation between barrier trial sectionals and subsequent race performance. The results are revealing.",
    author: 'James Alcott',
    status: 'published',
    category: 'Analysis',
    imageUrl: 'https://images.pexels.com/photos/2123375/pexels-photo-2123375.jpeg',
    linkedHorseIds: [],
    tags: ['barrier trial', 'sectionals', 'form analysis'],
    readingTime: 8,
    publishedAt: new Date('2025-09-05T07:00:00Z'),
    createdAt: new Date('2025-09-04T18:00:00Z'),
  },
  {
    id: 'art-024',
    title: "Group 1 Winners: Where Are They Now?",
    summary:
      "We tracked down twenty Australian-bred Group 1 winners from the 2019-2022 era. Some retired to stud at seven figures. Others were quietly sold abroad. One is still racing — right here in Australia.",
    author: 'Eleanor Hartley',
    status: 'published',
    category: 'Feature',
    imageUrl: 'https://images.pexels.com/photos/1996333/pexels-photo-1996333.jpeg',
    linkedHorseIds: [],
    tags: ['group 1', 'retrospective', 'feature'],
    readingTime: 10,
    publishedAt: new Date('2025-08-25T08:00:00Z'),
    createdAt: new Date('2025-08-24T16:00:00Z'),
  },
];

// ─── Horses ───────────────────────────────────────────────────────────────────
export const horses: Horse[] = [...SEED_HORSES];

// ─── Parties ──────────────────────────────────────────────────────────────────
export const parties: Party[] = [...SEED_PARTIES_ALL];

// ─── HorsePartyLinks ──────────────────────────────────────────────────────────
export const horsePartyLinks: HorsePartyLink[] = [
  {
    id: 'link-001',
    createdAt: new Date('2024-01-01T00:00:00Z'),
    horse_id: 'seed-savile-row-001',
    party_id: 'seed-party-ciaron-maher-001',
    relationship_type: 'training',
    start_date: '2023-01-01',
    end_date: null,
    context: 'Current trainer — Caulfield base',
  },
  {
    id: 'link-002',
    createdAt: new Date('2024-01-01T00:00:00Z'),
    horse_id: 'seed-savile-row-001',
    party_id: 'seed-party-michael-christian-001',
    relationship_type: 'ownership',
    start_date: '2021-08-15',
    end_date: null,
    context: 'Purchased at 2021 Magic Millions',
  },
  {
    id: 'link-003',
    createdAt: new Date('2024-01-01T00:00:00Z'),
    horse_id: 'seed-savile-row-001',
    party_id: 'seed-party-damian-hogan-001',
    relationship_type: 'riding',
    start_date: '2024-03-01',
    end_date: null,
    context: 'Current stable jockey',
  },
  {
    id: 'link-004',
    createdAt: new Date('2024-02-01T00:00:00Z'),
    horse_id: 'seed-northern-star-001',
    party_id: 'seed-party-ron-hutchings-001',
    relationship_type: 'training',
    start_date: '2023-06-01',
    end_date: null,
    context: 'Current trainer — Eagle Farm base',
  },
  {
    id: 'link-005',
    createdAt: new Date('2024-03-01T00:00:00Z'),
    horse_id: 'seed-desert-queen-001',
    party_id: 'seed-party-oshea-john-001',
    relationship_type: 'training',
    start_date: '2022-11-01',
    end_date: null,
    context: 'Current trainer — Randwick base',
  },
  {
    id: 'link-006',
    createdAt: new Date('2024-04-01T00:00:00Z'),
    horse_id: 'seed-iron-monarch-001',
    party_id: 'seed-party-charlie-whitfield-001',
    relationship_type: 'training',
    start_date: '2020-04-01',
    end_date: null,
    context: 'Long-term trainer — Mornington base',
  },
];

// ─── Media Items ──────────────────────────────────────────────────────────────
export const mediaItems: MediaItem[] = [
  {
    id: 'media-001',
    createdAt: new Date('2025-09-12T09:00:00Z'),
    horse_id: 'seed-savile-row-001',
    subject: 'Flemington Cox Plate prep win — race winner photo',
    media_type: 'Photo',
    title: 'Savile Row Wins at Flemington — September 2025',
    source_publication: 'Racing Australia Photography',
    published_date: '2025-09-12',
    url: 'https://images.pexels.com/photos/1996333/pexels-photo-1996333.jpeg',
    featured_party_ids: ['seed-party-damian-hogan-001', 'seed-party-ciaron-maher-001'],
    linked_article_id: 'art-001',
  },
  {
    id: 'media-002',
    createdAt: new Date('2025-09-01T08:00:00Z'),
    horse_id: 'seed-savile-row-001',
    subject: "Feature profile on Ciaron Maher's training operation and Savile Row's spring campaign",
    media_type: 'Article',
    title: 'The Quiet Genius of Ciaron Maher — Stable Press Feature',
    source_publication: 'Stable Press',
    published_date: '2025-09-01',
    url: '/articles/art-006',
    featured_party_ids: ['seed-party-ciaron-maher-001'],
    linked_article_id: 'art-006',
  },
  {
    id: 'media-003',
    createdAt: new Date('2025-09-10T12:00:00Z'),
    horse_id: 'seed-savile-row-001',
    subject: 'Trackwork footage at Caulfield — final barrier trial before Flemington',
    media_type: 'Video',
    title: 'Savile Row — Caulfield Trackwork September 2025',
    source_publication: 'Stable Press Media',
    published_date: '2025-09-10',
    url: 'https://www.youtube.com/watch?v=example',
    featured_party_ids: ['seed-party-ciaron-maher-001', 'seed-party-damian-hogan-001'],
    linked_article_id: undefined,
  },
  {
    id: 'media-004',
    createdAt: new Date('2025-09-08T14:00:00Z'),
    horse_id: 'seed-savile-row-001',
    subject: 'Spring Carnival form guide — Savile Row highlighted as flagship runner',
    media_type: 'Publication',
    title: 'The Spring Carnival Blueprint: Five Horses to Follow',
    source_publication: 'Stable Press',
    published_date: '2025-09-08',
    url: '/articles/art-002',
    featured_party_ids: [],
    linked_article_id: 'art-002',
  },
  {
    id: 'media-005',
    createdAt: new Date('2025-08-20T10:00:00Z'),
    horse_id: 'seed-savile-row-001',
    subject: 'Official press release ahead of Cox Plate nomination',
    media_type: 'Press Release',
    title: 'Savile Row Nominated for Cox Plate — Connections Statement',
    source_publication: 'Ciaron Maher Racing',
    published_date: '2025-08-20',
    url: undefined,
    file_name: 'savile-row-cox-plate-nomination-press-release.pdf',
    featured_party_ids: ['seed-party-ciaron-maher-001', 'seed-party-michael-christian-001'],
    linked_article_id: undefined,
  },
  // Northern Star
  {
    id: 'media-006',
    createdAt: new Date('2025-08-28T10:00:00Z'),
    horse_id: 'seed-northern-star-001',
    subject: "Spotlight article following Northern Star's Brisbane winter campaign",
    media_type: 'Article',
    title: 'Northern Star Chases Brisbane Glory After Stunning Winter Campaign',
    source_publication: 'Stable Press',
    published_date: '2025-08-28',
    url: '/articles/art-003',
    featured_party_ids: ['seed-party-ron-hutchings-001'],
    linked_article_id: 'art-003',
  },
  {
    id: 'media-007',
    createdAt: new Date('2025-09-06T12:00:00Z'),
    horse_id: 'seed-northern-star-001',
    subject: 'Eagle Farm trackwork gallery — spring carnival preparation shots',
    media_type: 'Photo',
    title: 'Northern Star Eagle Farm Trackwork — Spring 2025',
    source_publication: 'Racing Queensland Photography',
    published_date: '2025-09-05',
    url: 'https://images.pexels.com/photos/635499/pexels-photo-635499.jpeg',
    featured_party_ids: ['seed-party-ron-hutchings-001'],
    linked_article_id: undefined,
  },
  // Desert Queen
  {
    id: 'media-008',
    createdAt: new Date('2025-09-03T11:00:00Z'),
    horse_id: 'seed-desert-queen-001',
    subject: 'Profile feature on Desert Queen competing in open company',
    media_type: 'Article',
    title: "Desert Queen: The Mare Taking On the Boys",
    source_publication: 'Stable Press',
    published_date: '2025-09-03',
    url: '/articles/art-004',
    featured_party_ids: ['seed-party-oshea-john-001'],
    linked_article_id: 'art-004',
  },
  {
    id: 'media-009',
    createdAt: new Date('2025-09-18T11:00:00Z'),
    horse_id: 'seed-desert-queen-001',
    subject: "Race report from Randwick five-length Autumn win",
    media_type: 'Article',
    title: 'Desert Queen Crushes the Autumn Final Field — Race Report',
    source_publication: 'Stable Press',
    published_date: '2025-09-18',
    url: '/articles/art-013',
    featured_party_ids: ['seed-party-oshea-john-001'],
    linked_article_id: 'art-013',
  },
  {
    id: 'media-010',
    createdAt: new Date('2025-09-23T09:00:00Z'),
    horse_id: 'seed-desert-queen-001',
    subject: "Owner Katherine Dunmore's twelve-month diary — published in full",
    media_type: 'Publication',
    title: "Owner's Diary: Twelve Months with Desert Queen",
    source_publication: 'Stable Press',
    published_date: '2025-09-23',
    url: '/articles/art-021',
    featured_party_ids: [],
    linked_article_id: 'art-021',
  },
  {
    id: 'media-011',
    createdAt: new Date('2025-09-20T15:00:00Z'),
    horse_id: 'seed-desert-queen-001',
    subject: 'Winner photo from Randwick Autumn final',
    media_type: 'Photo',
    title: 'Desert Queen — Randwick Winner Photo September 2025',
    source_publication: 'Racing NSW Photography',
    published_date: '2025-09-18',
    url: 'https://images.pexels.com/photos/1571939/pexels-photo-1571939.jpeg',
    featured_party_ids: [],
    linked_article_id: 'art-013',
  },
  // Iron Monarch
  {
    id: 'media-012',
    createdAt: new Date('2025-09-06T23:30:00Z'),
    horse_id: 'seed-iron-monarch-001',
    subject: 'Race report from Moonee Valley night meeting win',
    media_type: 'Article',
    title: 'Iron Monarch Claims Moonee Valley Night Crown',
    source_publication: 'Stable Press',
    published_date: '2025-09-06',
    url: '/articles/art-009',
    featured_party_ids: ['seed-party-charlie-whitfield-001'],
    linked_article_id: 'art-009',
  },
  {
    id: 'media-013',
    createdAt: new Date('2025-09-09T09:00:00Z'),
    horse_id: 'seed-iron-monarch-001',
    subject: "Profile: Iron Monarch's 24-start career and refusal to step back from competition",
    media_type: 'Article',
    title: 'Iron Monarch at 24: The Gelding Who Refuses to Quit',
    source_publication: 'Stable Press',
    published_date: '2025-09-09',
    url: '/articles/art-016',
    featured_party_ids: ['seed-party-charlie-whitfield-001'],
    linked_article_id: 'art-016',
  },
  {
    id: 'media-014',
    createdAt: new Date('2025-09-08T08:00:00Z'),
    horse_id: 'seed-iron-monarch-001',
    subject: 'Moonee Valley winner photo under lights',
    media_type: 'Photo',
    title: 'Iron Monarch — Moonee Valley Night Win Photo',
    source_publication: 'Racing Victoria Photography',
    published_date: '2025-09-06',
    url: 'https://images.pexels.com/photos/1995842/pexels-photo-1995842.jpeg',
    featured_party_ids: ['seed-party-charlie-whitfield-001'],
    linked_article_id: 'art-009',
  },
];

// ─── Sales ──────────────────────────────────────────────────────────────────
export const sales: Sale[] = [
  {
    id: 'sale-001',
    createdAt: new Date('2021-08-15T00:00:00Z'),
    horse_id: 'seed-savile-row-001',
    sale_date: '2021-08-15',
    sale_type: 'Yearling Sale',
    venue: 'Magic Millions Gold Coast',
    lot: 'Lot 412',
    price: 420000,
    currency: 'AUD',
    buyer_party_id: 'seed-party-michael-christian-001',
    vendor: 'Newgate Stud',
    notes: 'Knocked down to Porter Pelchen Bloodstock on behalf of the Christian family.',
  },
  {
    id: 'sale-002',
    createdAt: new Date('2020-05-10T00:00:00Z'),
    horse_id: 'seed-savile-row-001',
    sale_date: '2020-05-10',
    sale_type: 'Weanling Sale',
    venue: 'Inglis Easter',
    lot: 'Lot 88',
    price: 165000,
    currency: 'AUD',
    vendor: 'Trelawny Stud',
  },
  {
    id: 'sale-003',
    createdAt: new Date('2022-11-01T00:00:00Z'),
    horse_id: 'seed-desert-queen-001',
    sale_date: '2022-11-01',
    sale_type: 'Yearling Sale',
    venue: 'Karaka Book 1',
    lot: 'Lot 204',
    price: 280000,
    currency: 'NZD',
    vendor: "O'Shea Bloodstock",
  },
];

// ─── Reports / Forms ──────────────────────────────────────────────────────────
export const reports: HorseReport[] = [
  {
    id: 'report-001',
    createdAt: new Date('2013-10-01T00:00:00Z'),
    horse_id: 'seed-savile-row-001',
    doc_type: 'Registration',
    title: 'Australian Stud Book Certificate of Registration',
    issued_date: '2013-10-01',
    issuing_body: 'Racing Australia',
    visibility: 'public',
  },
  {
    id: 'report-002',
    createdAt: new Date('2025-08-01T00:00:00Z'),
    horse_id: 'seed-savile-row-001',
    doc_type: 'Passport',
    title: 'Thoroughbred Identification Passport',
    issued_date: '2014-01-15',
    issuing_body: 'Racing Australia',
    visibility: 'public',
  },
  {
    id: 'report-003',
    createdAt: new Date('2025-09-08T00:00:00Z'),
    horse_id: 'seed-savile-row-001',
    doc_type: 'Vet Report',
    title: 'Pre-Cox Plate Veterinary Soundness Examination',
    issued_date: '2025-09-08',
    issuing_body: 'Flemington Equine Clinic',
    visibility: 'restricted',
  },
  {
    id: 'report-004',
    createdAt: new Date('2025-09-10T00:00:00Z'),
    horse_id: 'seed-savile-row-001',
    doc_type: 'X-Ray / Scan',
    title: 'Off-fore fetlock radiograph series',
    issued_date: '2025-09-10',
    issuing_body: 'Flemington Equine Clinic',
    visibility: 'restricted',
  },
];

// ─── Racing Entries ───────────────────────────────────────────────────────────
export const racingEntries: RacingEntry[] = [
  {
    id: 'race-entry-001',
    createdAt: new Date('2025-09-12T08:00:00Z'),
    horse_id: 'seed-savile-row-001',
    subject: 'Cox Plate prep — Flemington win',
    race_name: 'Turnbull Stakes',
    race_date: '2025-09-12',
    venue: 'Flemington',
    country: 'Australia',
    class_grade: 'Gr.1',
    distance: '2000m',
    track_condition: 'Good (3)',
    status: 'Finished',
    finish_position: 1,
    margin: 'Nose',
    time: '2:00.1',
    prize_money: 450000,
    barrier: 4,
    weight_carried: '57kg',
    jockey_id: 'seed-party-damian-hogan-001',
    trainer_id: 'seed-party-ciaron-maher-001',
  },
  {
    id: 'race-entry-002',
    createdAt: new Date('2025-10-05T08:00:00Z'),
    horse_id: 'seed-savile-row-001',
    subject: 'Cox Plate nomination accepted',
    race_name: 'Cox Plate',
    race_date: '2025-10-25',
    venue: 'Moonee Valley',
    country: 'Australia',
    class_grade: 'Gr.1',
    distance: '2040m',
    track_condition: 'Good',
    status: 'Accepted',
    barrier: 5,
    weight_carried: '57kg',
    jockey_id: 'seed-party-damian-hogan-001',
    trainer_id: 'seed-party-ciaron-maher-001',
  },
  {
    id: 'race-entry-003',
    createdAt: new Date('2025-09-06T22:30:00Z'),
    horse_id: 'seed-iron-monarch-001',
    subject: 'Moonee Valley night meeting win — career highlight',
    race_name: 'Moonee Valley Stakes',
    race_date: '2025-09-06',
    venue: 'Moonee Valley',
    country: 'Australia',
    class_grade: 'Listed',
    distance: '1600m',
    track_condition: 'Good (4)',
    status: 'Finished',
    finish_position: 1,
    margin: '1.2L',
    time: '1:35.4',
    prize_money: 130000,
    barrier: 2,
    weight_carried: '56.5kg',
    trainer_id: 'seed-party-charlie-whitfield-001',
  },
  {
    id: 'race-entry-004',
    createdAt: new Date('2025-09-03T10:00:00Z'),
    horse_id: 'seed-desert-queen-001',
    subject: 'Dominant 5-length Randwick win in Autumn Final',
    race_name: 'Randwick Autumn Final',
    race_date: '2025-09-18',
    venue: 'Royal Randwick',
    country: 'Australia',
    class_grade: 'Gr.2',
    distance: '2000m',
    track_condition: 'Soft (5)',
    status: 'Finished',
    finish_position: 1,
    margin: '5L',
    time: '2:03.8',
    prize_money: 250000,
    barrier: 3,
    weight_carried: '55kg',
    trainer_id: 'seed-party-oshea-john-001',
  },
  {
    id: 'race-entry-005',
    createdAt: new Date('2025-08-20T10:00:00Z'),
    horse_id: 'seed-northern-star-001',
    subject: 'Doomben Cup win — winter campaign highlight',
    race_name: 'Doomben Cup',
    race_date: '2025-08-17',
    venue: 'Doomben',
    country: 'Australia',
    class_grade: 'Gr.2',
    distance: '2000m',
    track_condition: 'Good (3)',
    status: 'Finished',
    finish_position: 1,
    margin: '2.5L',
    time: '2:02.6',
    prize_money: 300000,
    barrier: 1,
    weight_carried: '57.5kg',
    trainer_id: 'seed-party-ron-hutchings-001',
  },
];

// ─── Races ────────────────────────────────────────────────────────────────────
export const races: Race[] = [
  {
    id: 'race-001',
    name: 'Turnbull Stakes',
    venue: 'Flemington Racecourse',
    distance: '2000m',
    scheduledAt: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'open',
    entrants: [
      { horseId: 'seed-savile-row-001', horseName: 'Savile Row', jockey: 'D. Hogan', odds: 3.5, barrierNumber: 4 },
      { horseId: 'seed-northern-star-001', horseName: 'Northern Star', jockey: 'J. McDonald', odds: 4.2, barrierNumber: 7 },
      { horseId: 'seed-iron-monarch-001', horseName: 'Iron Monarch', jockey: 'C. Williams', odds: 6.0, barrierNumber: 2 },
      { horseId: 'ent-turnbull-4', horseName: 'Highland Reel', jockey: 'R. Mallyon', odds: 8.5, barrierNumber: 11 },
      { horseId: 'ent-turnbull-5', horseName: 'Crystal Palace', jockey: 'L. Nolen', odds: 12.0, barrierNumber: 1 },
      { horseId: 'ent-turnbull-6', horseName: 'Amber Tide', jockey: 'M. Dee', odds: 5.5, barrierNumber: 9 },
      { horseId: 'ent-turnbull-7', horseName: 'Sovereign Streak', jockey: 'T. Berry', odds: 9.0, barrierNumber: 6 },
      { horseId: 'ent-turnbull-8', horseName: 'Midnight Phantom', jockey: 'H. Bowman', odds: 15.0, barrierNumber: 14 },
    ],
    winnerHorseId: null,
    createdAt: new Date('2025-09-01T00:00:00Z').toISOString(),
    lat: -37.7883,
    lng: 144.9149,
  },
  {
    id: 'race-002',
    name: 'Caulfield Guineas',
    venue: 'Caulfield Racecourse',
    distance: '1600m',
    scheduledAt: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'open',
    entrants: [
      { horseId: 'seed-desert-queen-001', horseName: 'Desert Queen', jockey: 'M. Rodd', odds: 2.8, barrierNumber: 3 },
      { horseId: 'ent-guinea-2', horseName: 'Starlight Express', jockey: 'H. Bowman', odds: 5.0, barrierNumber: 6 },
      { horseId: 'ent-guinea-3', horseName: 'Rapid Fire', jockey: 'T. Berry', odds: 7.0, barrierNumber: 10 },
      { horseId: 'ent-guinea-4', horseName: 'Golden Thread', jockey: 'J. Cassidy', odds: 9.0, barrierNumber: 2 },
      { horseId: 'ent-guinea-5', horseName: 'Sea Breeze', jockey: 'D. Oliver', odds: 14.0, barrierNumber: 5 },
      { horseId: 'ent-guinea-6', horseName: 'Red Admiral', jockey: 'M. Walker', odds: 4.5, barrierNumber: 8 },
      { horseId: 'ent-guinea-7', horseName: 'Champagne Prince', jockey: 'R. Waller', odds: 11.0, barrierNumber: 1 },
    ],
    winnerHorseId: null,
    createdAt: new Date('2025-09-01T00:00:00Z').toISOString(),
    lat: -37.8786,
    lng: 145.0217,
  },
  {
    id: 'race-003',
    name: 'Cox Plate',
    venue: 'Moonee Valley Racecourse',
    distance: '2040m',
    scheduledAt: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'upcoming',
    entrants: [
      { horseId: 'seed-savile-row-001', horseName: 'Savile Row', jockey: 'D. Hogan', odds: 4.0, barrierNumber: 5 },
      { horseId: 'seed-iron-monarch-001', horseName: 'Iron Monarch', jockey: 'C. Williams', odds: 5.5, barrierNumber: 3 },
      { horseId: 'ent-cox-3', horseName: 'Dublin Dancer', jockey: 'R. Moore', odds: 3.2, barrierNumber: 1 },
      { horseId: 'ent-cox-4', horseName: 'Black Caviar II', jockey: 'L. Dettori', odds: 8.0, barrierNumber: 8 },
      { horseId: 'ent-cox-5', horseName: 'Pacific Storm', jockey: 'J. McDonald', odds: 6.5, barrierNumber: 6 },
      { horseId: 'ent-cox-6', horseName: 'English River', jockey: 'H. Bowman', odds: 12.0, barrierNumber: 4 },
    ],
    winnerHorseId: null,
    createdAt: new Date('2025-09-01T00:00:00Z').toISOString(),
    lat: -37.7517,
    lng: 144.9271,
  },
  {
    id: 'race-004',
    name: 'Melbourne Cup',
    venue: 'Flemington Racecourse',
    distance: '3200m',
    scheduledAt: new Date(Date.now() + 35 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'upcoming',
    entrants: [
      { horseId: 'seed-northern-star-001', horseName: 'Northern Star', jockey: 'J. McDonald', odds: 6.0, barrierNumber: 12 },
      { horseId: 'ent-cup-2', horseName: 'Santiago Bay', jockey: 'F. Dettori', odds: 9.0, barrierNumber: 4 },
      { horseId: 'ent-cup-3', horseName: 'Vow And Declare II', jockey: 'D. Payne', odds: 11.0, barrierNumber: 7 },
      { horseId: 'ent-cup-4', horseName: 'Prince of Arran', jockey: 'C. Soumillon', odds: 15.0, barrierNumber: 19 },
      { horseId: 'ent-cup-5', horseName: 'Gold Trip', jockey: 'M. Rodd', odds: 7.5, barrierNumber: 3 },
      { horseId: 'ent-cup-6', horseName: "Twilight's Edge", jockey: 'H. Bowman', odds: 12.0, barrierNumber: 14 },
      { horseId: 'ent-cup-7', horseName: 'Lord Riviera', jockey: 'J. Cassidy', odds: 18.0, barrierNumber: 8 },
      { horseId: 'ent-cup-8', horseName: 'Persan', jockey: 'T. Berry', odds: 21.0, barrierNumber: 22 },
    ],
    winnerHorseId: null,
    createdAt: new Date('2025-09-01T00:00:00Z').toISOString(),
    lat: -37.7883,
    lng: 144.9149,
  },
  {
    id: 'race-005',
    name: 'Doomben Cup',
    venue: 'Doomben Racecourse',
    distance: '2000m',
    scheduledAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'resolved',
    entrants: [
      { horseId: 'seed-northern-star-001', horseName: 'Northern Star', jockey: 'J. McDonald', odds: 2.9, barrierNumber: 1 },
      { horseId: 'ent-doom-2', horseName: 'Jungle Edge', jockey: 'T. Berry', odds: 6.0, barrierNumber: 5 },
      { horseId: 'ent-doom-3', horseName: 'Graff', jockey: 'R. Maloney', odds: 4.5, barrierNumber: 3 },
      { horseId: 'ent-doom-4', horseName: 'Flying Artie II', jockey: 'M. Dee', odds: 8.0, barrierNumber: 7 },
    ],
    winnerHorseId: 'seed-northern-star-001',
    createdAt: new Date('2025-09-01T00:00:00Z').toISOString(),
    lat: -27.4340,
    lng: 153.0474,
  },
  {
    id: 'race-006',
    name: 'Moonee Valley Stakes',
    venue: 'Moonee Valley Racecourse',
    distance: '1600m',
    scheduledAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'resolved',
    entrants: [
      { horseId: 'seed-iron-monarch-001', horseName: 'Iron Monarch', jockey: 'C. Williams', odds: 3.8, barrierNumber: 2 },
      { horseId: 'ent-mv-2', horseName: 'Amber Tide', jockey: 'M. Dee', odds: 5.5, barrierNumber: 6 },
      { horseId: 'ent-mv-3', horseName: 'Sovereign Streak', jockey: 'L. Nolen', odds: 4.2, barrierNumber: 4 },
      { horseId: 'ent-mv-4', horseName: 'Crystal Palace', jockey: 'T. Berry', odds: 9.0, barrierNumber: 8 },
    ],
    winnerHorseId: 'seed-iron-monarch-001',
    createdAt: new Date('2025-09-01T00:00:00Z').toISOString(),
    lat: -37.7517,
    lng: 144.9271,
  },
  {
    id: 'race-007',
    name: 'Brisbane Classic',
    venue: 'Eagle Farm Racecourse',
    distance: '2400m',
    scheduledAt: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'upcoming',
    entrants: [
      { horseId: 'seed-northern-star-001', horseName: 'Northern Star', jockey: 'J. McDonald', odds: 3.0, barrierNumber: 5 },
      { horseId: 'ent-bris-2', horseName: 'Gold Trip', jockey: 'M. Rodd', odds: 5.0, barrierNumber: 3 },
      { horseId: 'ent-bris-3', horseName: 'Vow And Declare II', jockey: 'D. Payne', odds: 7.0, barrierNumber: 9 },
      { horseId: 'ent-bris-4', horseName: 'Prince of Arran', jockey: 'H. Bowman', odds: 10.0, barrierNumber: 1 },
      { horseId: 'ent-bris-5', horseName: 'Persan', jockey: 'T. Berry', odds: 14.0, barrierNumber: 7 },
    ],
    winnerHorseId: null,
    createdAt: new Date('2025-09-01T00:00:00Z').toISOString(),
    lat: -27.4340,
    lng: 153.0637,
  },
];

// ─── Tips ─────────────────────────────────────────────────────────────────────
export const tips: Tip[] = [
  // Turnbull Stakes tips
  {
    id: 'tip-001',
    userId: 'demo-tipper-1',
    raceId: 'race-001',
    horseName: 'Savile Row',
    horseId: 'seed-savile-row-001',
    wager: 100,
    odds: 3.5,
    payout: null,
    result: 'pending',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tip-002',
    userId: 'demo-tipper-2',
    raceId: 'race-001',
    horseName: 'Amber Tide',
    horseId: 'ent-turnbull-6',
    wager: 75,
    odds: 5.5,
    payout: null,
    result: 'pending',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tip-009',
    userId: 'demo-tipper-4',
    raceId: 'race-001',
    horseName: 'Northern Star',
    horseId: 'seed-northern-star-001',
    wager: 150,
    odds: 4.2,
    payout: null,
    result: 'pending',
    createdAt: new Date().toISOString(),
  },
  // Caulfield Guineas tips
  {
    id: 'tip-010',
    userId: 'demo-tipper-3',
    raceId: 'race-002',
    horseName: 'Desert Queen',
    horseId: 'seed-desert-queen-001',
    wager: 200,
    odds: 2.8,
    payout: null,
    result: 'pending',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tip-011',
    userId: 'demo-tipper-5',
    raceId: 'race-002',
    horseName: 'Red Admiral',
    horseId: 'ent-guinea-6',
    wager: 80,
    odds: 4.5,
    payout: null,
    result: 'pending',
    createdAt: new Date().toISOString(),
  },
  // Resolved — Doomben Cup
  {
    id: 'tip-003',
    userId: 'demo-tipper-3',
    raceId: 'race-005',
    horseName: 'Northern Star',
    horseId: 'seed-northern-star-001',
    wager: 200,
    odds: 2.9,
    payout: 580,
    result: 'won',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tip-012',
    userId: 'demo-tipper-1',
    raceId: 'race-005',
    horseName: 'Jungle Edge',
    horseId: 'ent-doom-2',
    wager: 50,
    odds: 6.0,
    payout: 0,
    result: 'lost',
    createdAt: new Date().toISOString(),
  },
  // Resolved — Moonee Valley Stakes
  {
    id: 'tip-013',
    userId: 'demo-tipper-2',
    raceId: 'race-006',
    horseName: 'Iron Monarch',
    horseId: 'seed-iron-monarch-001',
    wager: 120,
    odds: 3.8,
    payout: 456,
    result: 'won',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tip-014',
    userId: 'demo-tipper-6',
    raceId: 'race-006',
    horseName: 'Sovereign Streak',
    horseId: 'ent-mv-3',
    wager: 90,
    odds: 4.2,
    payout: 0,
    result: 'lost',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tip-015',
    userId: 'demo-tipper-7',
    raceId: 'race-006',
    horseName: 'Iron Monarch',
    horseId: 'seed-iron-monarch-001',
    wager: 60,
    odds: 3.8,
    payout: 228,
    result: 'won',
    createdAt: new Date().toISOString(),
  },
];

// ─── Podcast Episodes ─────────────────────────────────────────────────────────
export const podcastEpisodes: PodcastEpisode[] = [
  {
    id: 'pod-001',
    title: 'Spring Carnival Preview: Who Wins the Big Four?',
    description:
      'Host Patrick Gillespie sits down with former champion jockey Shane McGrath and international bloodstock expert Claire Henton to dissect the form ahead of the Melbourne Cup, Cox Plate, Caulfield Cup, and Turnbull Stakes. This is the essential listen before the carnival begins.',
    host: 'Patrick Gillespie',
    durationSeconds: 3240,
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
    publishedAt: '2025-09-10T06:00:00Z',
    relatedArticleIds: ['art-002', 'art-005'],
    coverUrl: 'https://images.pexels.com/photos/1181671/pexels-photo-1181671.jpeg',
    season: 3,
    episodeNumber: 8,
    createdAt: '2025-09-08T10:00:00Z',
    status: 'published',
    guests: [
      { id: 'g-001', name: 'Shane McGrath', title: 'Former Champion Jockey', bio: '4 Melbourne Cup wins' },
      { id: 'g-002', name: 'Claire Henton', title: 'International Bloodstock Expert' },
    ],
    distributionChannels: ['spotify', 'apple_podcasts', 'website', 'rss_feed'],
    scheduledFor: '2025-09-10T06:00:00Z',
    producedBy: 'Eleanor Hartley',
  },
  {
    id: 'pod-002',
    title: 'Inside the Stable: Ciaron Maher on Savile Row and the Group 1 Target',
    description:
      "Rare access to Caulfield track work at 5am. Patrick Gillespie joins champion trainer Ciaron Maher as Savile Row breezes through his final piece before the Turnbull. Maher reveals the Cox Plate plan, the horse's mental preparation, and how the spring target was set.",
    host: 'Patrick Gillespie',
    durationSeconds: 2760,
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
    publishedAt: '2025-09-04T06:00:00Z',
    relatedArticleIds: ['art-001', 'art-006'],
    coverUrl: 'https://images.pexels.com/photos/1639729/pexels-photo-1639729.jpeg',
    season: 3,
    episodeNumber: 7,
    createdAt: '2025-09-02T11:00:00Z',
    status: 'published',
    guests: [
      { id: 'g-003', name: 'Ciaron Maher', title: 'Champion Trainer', bio: 'Multiple Group 1 winning trainer' },
    ],
    distributionChannels: ['spotify', 'apple_podcasts', 'website'],
    scheduledFor: '2025-09-04T06:00:00Z',
    producedBy: 'Stephanie Voss',
  },
  {
    id: 'pod-003',
    title: 'The Bloodstock Report: Magic Millions Yearling Sales Analysis',
    description:
      'Our bloodstock team reviews the top 20 lots from the Magic Millions yearling sales, identifying the horses likely to land in Melbourne stables for the 2026 spring carnival. Value buys, standout pedigrees, and the agents who shaped the market.',
    host: 'Eleanor Hartley',
    durationSeconds: 4140,
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
    publishedAt: '2025-08-22T06:00:00Z',
    relatedArticleIds: ['art-007', 'art-012'],
    coverUrl: 'https://images.pexels.com/photos/2291264/pexels-photo-2291264.jpeg',
    season: 3,
    episodeNumber: 6,
    createdAt: '2025-08-20T09:00:00Z',
    status: 'published',
    guests: [
      { id: 'g-004', name: 'James Porter', title: 'Head of Porter Pelchen Bloodstock' },
      { id: 'g-005', name: 'Natasha Kline', title: 'Magic Millions Sales Director' },
    ],
    distributionChannels: ['spotify', 'apple_podcasts', 'website', 'newsletter', 'rss_feed'],
    scheduledFor: '2025-08-22T06:00:00Z',
    producedBy: 'James Alcott',
  },
  {
    id: 'pod-004',
    title: "Desert Queen: The Story Behind the Mare Taking On the World",
    description:
      "Stephanie Voss interviews trainer John O'Shea and owner Katherine Dunmore about the meteoric rise of Desert Queen. How a filly nobody bid on at the sales became the horse everyone is talking about.",
    host: 'Stephanie Voss',
    durationSeconds: 3600,
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
    publishedAt: '2025-09-07T06:00:00Z',
    relatedArticleIds: ['art-004'],
    coverUrl: 'https://images.pexels.com/photos/1571939/pexels-photo-1571939.jpeg',
    season: 3,
    episodeNumber: 8,
    createdAt: '2025-09-05T14:00:00Z',
    status: 'published',
    guests: [
      { id: 'g-006', name: "John O'Shea", title: 'Champion Trainer' },
      { id: 'g-007', name: 'Katherine Dunmore', title: 'Owner' },
    ],
    distributionChannels: ['spotify', 'apple_podcasts', 'website'],
    scheduledFor: '2025-09-07T06:00:00Z',
    producedBy: 'Stephanie Voss',
  },
  {
    id: 'pod-005',
    title: 'Road to the Melbourne Cup: History, Legends, and 2025 Contenders',
    description:
      "Three thousand two hundred metres that capture the attention of a nation. We go deep on the Melbourne Cup's history, the horses that defined it, and why the 2025 field may be the most globally competitive in a decade.",
    host: 'James Alcott',
    durationSeconds: 4800,
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
    publishedAt: '',
    relatedArticleIds: ['art-008'],
    coverUrl: 'https://images.pexels.com/photos/1996333/pexels-photo-1996333.jpeg',
    season: 3,
    episodeNumber: 9,
    createdAt: '2025-09-15T09:00:00Z',
    status: 'in_review',
    guests: [
      { id: 'g-008', name: 'Bart Cummings Jr.', title: 'Racing Historian' },
    ],
    distributionChannels: ['spotify', 'apple_podcasts'],
    scheduledFor: '2025-09-20T06:00:00Z',
    producedBy: 'James Alcott',
    reviewNotes: 'Waiting on final fact-check for Cup winners section. Audio mix signed off.',
  },
  {
    id: 'pod-007',
    title: 'Craig Williams: Riding at the Top for Twenty-Five Years',
    description:
      "Craig Williams has been riding Group 1 winners since before some of his rivals were born. Patrick Gillespie sits with the champion for an extended conversation about longevity, horsemanship, and the art of the waiting ride.",
    host: 'Patrick Gillespie',
    durationSeconds: 3900,
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3',
    publishedAt: '2025-09-14T06:00:00Z',
    relatedArticleIds: ['art-016'],
    coverUrl: 'https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg',
    season: 3,
    episodeNumber: 10,
    createdAt: '2025-09-12T10:00:00Z',
    status: 'published',
    guests: [
      { id: 'g-009', name: 'Craig Williams', title: 'Champion Jockey', bio: '25 seasons at the top level' },
    ],
    distributionChannels: ['spotify', 'apple_podcasts', 'website', 'rss_feed'],
    scheduledFor: '2025-09-14T06:00:00Z',
    producedBy: 'Eleanor Hartley',
  },
  {
    id: 'pod-008',
    title: 'Track Conditions and Their Hidden Effect on Sectionals',
    description:
      "Not all soft tracks are the same. Not all good tracks are the same. Racing analyst Dr. Adrian Morley explains why the published going description tells only half the story — and how to use sectional data to find the truth underneath.",
    host: 'Eleanor Hartley',
    durationSeconds: 2880,
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
    publishedAt: '2025-09-17T06:00:00Z',
    relatedArticleIds: ['art-018', 'art-023'],
    coverUrl: 'https://images.pexels.com/photos/1181671/pexels-photo-1181671.jpeg',
    season: 3,
    episodeNumber: 11,
    createdAt: '2025-09-15T14:00:00Z',
    status: 'published',
    guests: [
      { id: 'g-010', name: 'Dr. Adrian Morley', title: 'Racing Analyst & Sectional Data Specialist' },
    ],
    distributionChannels: ['spotify', 'apple_podcasts', 'website'],
    scheduledFor: '2025-09-17T06:00:00Z',
    producedBy: 'Stephanie Voss',
  },
  {
    id: 'pod-009',
    title: 'The Art of the Stallion Selection: What the Market Misses',
    description:
      "Bloodstock agent Lara Saunders has placed eleven stakes winners from the pages of one notebook she has carried for nine years. Eleanor Hartley finds out what she looks for — and why the most popular stallion is almost never the right choice.",
    host: 'Eleanor Hartley',
    durationSeconds: 3480,
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
    publishedAt: '2025-08-28T06:00:00Z',
    relatedArticleIds: ['art-007'],
    coverUrl: 'https://images.pexels.com/photos/2291264/pexels-photo-2291264.jpeg',
    season: 3,
    episodeNumber: 5,
    createdAt: '2025-08-26T10:00:00Z',
    status: 'published',
    guests: [
      { id: 'g-011', name: 'Lara Saunders', title: 'Bloodstock Agent, Saunders Equine' },
    ],
    distributionChannels: ['spotify', 'apple_podcasts', 'website', 'newsletter'],
    scheduledFor: '2025-08-28T06:00:00Z',
    producedBy: 'Patrick Gillespie',
  },
  {
    id: 'pod-010',
    title: 'Iron Monarch: The Lonhro Son Who Refuses to Be Overlooked',
    description:
      "Twenty-four career starts. Eight wins. Over a million dollars in prizemoney. Iron Monarch is the most underrated horse in the country. His trainer Charlie Whitfield tells the full story — from the bargain purchase to Moonee Valley night glory.",
    host: 'James Alcott',
    durationSeconds: 2640,
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
    publishedAt: '2025-09-11T06:00:00Z',
    relatedArticleIds: ['art-009', 'art-016'],
    coverUrl: 'https://images.pexels.com/photos/1995842/pexels-photo-1995842.jpeg',
    season: 3,
    episodeNumber: 9,
    createdAt: '2025-09-09T13:00:00Z',
    status: 'published',
    guests: [
      { id: 'g-012', name: 'Charlie Whitfield', title: 'Trainer, Mornington Racing Centre' },
      { id: 'g-013', name: 'Craig Williams', title: 'Champion Jockey' },
    ],
    distributionChannels: ['spotify', 'apple_podcasts', 'website'],
    scheduledFor: '2025-09-11T06:00:00Z',
    producedBy: 'James Alcott',
  },
  {
    id: 'pod-006',
    title: "Season 4 Teaser: What's Coming in 2026",
    description:
      'A short teaser episode outlining the season 4 lineup — new co-hosts, a trackwork series, and exclusive paddock access.',
    host: 'Patrick Gillespie',
    durationSeconds: 480,
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
    publishedAt: '',
    relatedArticleIds: [],
    coverUrl: 'https://images.pexels.com/photos/1181346/pexels-photo-1181346.jpeg',
    season: 4,
    episodeNumber: 0,
    createdAt: '2025-09-17T10:00:00Z',
    status: 'draft',
    guests: [],
    distributionChannels: [],
    producedBy: 'Patrick Gillespie',
  },
];
