/**
 * Full seed dataset for Stable Press — horses, parties, and connections.
 * Includes the existing Savile Row seed plus additional thoroughbreds.
 */

import type { Horse } from '@/types/horse';
import type { Party } from '@/types/party';
import {
  SAVILE_ROW,
  SEED_PARTIES,
  SAVILE_ROW_ID,
} from '@/lib/seedHorses';

// ─── Additional Party IDs ─────────────────────────────────────────────────────
export const P_TRAINER_OJ    = 'seed-party-oshea-john-001';
export const P_OWNER_KD      = 'seed-party-katherine-dunmore-001';
export const P_JOCKEY_MR     = 'seed-party-mick-rodd-001';
export const P_TRAINER_RH    = 'seed-party-ron-hutchings-001';
export const P_OWNER_SS      = 'seed-party-summit-syndicate-001';
export const P_JOCKEY_JMC    = 'seed-party-james-mcdonald-001';
export const P_TRAINER_CW    = 'seed-party-charlie-whitfield-001';
export const P_OWNER_RM      = 'seed-party-ridgeline-mgmt-001';
export const P_JOCKEY_CWJ    = 'seed-party-craig-williams-001';
export const P_BREEDER_NS    = 'seed-party-newgate-stud-001';
export const P_BREEDER_SF    = 'seed-party-sunfire-farms-001';

// New party IDs for additional horses
export const P_TRAINER_SW    = 'seed-party-sarah-worthington-001';
export const P_TRAINER_ML    = 'seed-party-mike-lynch-001';
export const P_TRAINER_TH    = 'seed-party-tom-hayes-001';
export const P_OWNER_BF      = 'seed-party-blue-flag-racing-001';
export const P_OWNER_GC      = 'seed-party-glenora-corp-001';
export const P_OWNER_PL      = 'seed-party-paul-logan-001';
export const P_JOCKEY_TD     = 'seed-party-tim-donnelly-001';
export const P_JOCKEY_BH     = 'seed-party-blake-hunter-001';
export const P_JOCKEY_RC     = 'seed-party-rachel-cross-001';
export const P_BREEDER_KS    = 'seed-party-kingston-stud-001';
export const P_BREEDER_WP    = 'seed-party-windrush-park-001';
export const P_BREEDER_EP    = 'seed-party-eastern-plains-001';

// ─── Additional Parties ───────────────────────────────────────────────────────
const EXTRA_PARTIES: Party[] = [
  {
    id: P_TRAINER_OJ,
    createdAt: new Date('2024-01-01T00:00:00Z'),
    party_type: 'person',
    roles: ['trainer'],
    name: "John O'Shea",
    profession: 'Racehorse Trainer',
    started_year: 2001,
    base_location: 'Randwick, NSW',
    country_of_birth: 'Australia',
  },
  {
    id: P_OWNER_KD,
    createdAt: new Date('2024-01-01T00:00:00Z'),
    party_type: 'person',
    roles: ['owner'],
    name: 'Katherine Dunmore',
    profession: 'Thoroughbred Owner',
    started_year: 2018,
    country_of_birth: 'Australia',
  },
  {
    id: P_JOCKEY_MR,
    createdAt: new Date('2024-01-01T00:00:00Z'),
    party_type: 'person',
    roles: ['jockey'],
    name: 'Mick Rodd',
    profession: 'Jockey',
    started_year: 2008,
    country_of_birth: 'Australia',
  },
  {
    id: P_TRAINER_RH,
    createdAt: new Date('2024-01-01T00:00:00Z'),
    party_type: 'person',
    roles: ['trainer'],
    name: 'Ron Hutchings',
    profession: 'Racehorse Trainer',
    started_year: 2010,
    base_location: 'Eagle Farm, QLD',
    country_of_birth: 'Australia',
  },
  {
    id: P_OWNER_SS,
    createdAt: new Date('2024-01-01T00:00:00Z'),
    party_type: 'organisation',
    roles: ['owner'],
    name: 'Summit Racing Syndicate',
    profession: 'Racing Syndicate',
    started_year: 2015,
    base_location: 'Brisbane, QLD',
  },
  {
    id: P_JOCKEY_JMC,
    createdAt: new Date('2024-01-01T00:00:00Z'),
    party_type: 'person',
    roles: ['jockey'],
    name: 'James McDonald',
    profession: 'Jockey',
    started_year: 2012,
    country_of_birth: 'New Zealand',
  },
  {
    id: P_TRAINER_CW,
    createdAt: new Date('2024-01-01T00:00:00Z'),
    party_type: 'person',
    roles: ['trainer'],
    name: 'Charlie Whitfield',
    profession: 'Racehorse Trainer',
    started_year: 2008,
    base_location: 'Mornington, VIC',
    country_of_birth: 'Australia',
  },
  {
    id: P_OWNER_RM,
    createdAt: new Date('2024-01-01T00:00:00Z'),
    party_type: 'organisation',
    roles: ['owner'],
    name: 'Ridgeline Management Group',
    profession: 'Thoroughbred Management',
    base_location: 'Melbourne, VIC',
  },
  {
    id: P_JOCKEY_CWJ,
    createdAt: new Date('2024-01-01T00:00:00Z'),
    party_type: 'person',
    roles: ['jockey'],
    name: 'Craig Williams',
    profession: 'Jockey',
    started_year: 1999,
    country_of_birth: 'Australia',
  },
  {
    id: P_BREEDER_NS,
    createdAt: new Date('2024-01-01T00:00:00Z'),
    party_type: 'organisation',
    roles: ['breeder'],
    name: 'Newgate Stud',
    profession: 'Thoroughbred Stud Farm',
    base_location: 'Upper Hunter Valley, NSW',
    country_of_birth: 'Australia',
  },
  {
    id: P_BREEDER_SF,
    createdAt: new Date('2024-01-01T00:00:00Z'),
    party_type: 'organisation',
    roles: ['breeder'],
    name: 'Sunfire Farms',
    profession: 'Thoroughbred Stud Farm',
    base_location: 'Scone, NSW',
    country_of_birth: 'Australia',
  },
  // New parties for additional horses
  {
    id: P_TRAINER_SW,
    createdAt: new Date('2024-01-01T00:00:00Z'),
    party_type: 'person',
    roles: ['trainer'],
    name: 'Sarah Worthington',
    profession: 'Racehorse Trainer',
    started_year: 2014,
    base_location: 'Flemington, VIC',
    country_of_birth: 'Australia',
  },
  {
    id: P_TRAINER_ML,
    createdAt: new Date('2024-01-01T00:00:00Z'),
    party_type: 'person',
    roles: ['trainer'],
    name: 'Mike Lynch',
    profession: 'Racehorse Trainer',
    started_year: 2009,
    base_location: 'Caulfield, VIC',
    country_of_birth: 'Australia',
  },
  {
    id: P_TRAINER_TH,
    createdAt: new Date('2024-01-01T00:00:00Z'),
    party_type: 'person',
    roles: ['trainer'],
    name: 'Tom Hayes',
    profession: 'Racehorse Trainer',
    started_year: 2003,
    base_location: 'Lindsay Park, SA',
    country_of_birth: 'Australia',
  },
  {
    id: P_OWNER_BF,
    createdAt: new Date('2024-01-01T00:00:00Z'),
    party_type: 'organisation',
    roles: ['owner'],
    name: 'Blue Flag Racing',
    profession: 'Racing Partnership',
    started_year: 2019,
    base_location: 'Sydney, NSW',
  },
  {
    id: P_OWNER_GC,
    createdAt: new Date('2024-01-01T00:00:00Z'),
    party_type: 'organisation',
    roles: ['owner'],
    name: 'Glenora Corporation',
    profession: 'Thoroughbred Owner',
    base_location: 'Melbourne, VIC',
  },
  {
    id: P_OWNER_PL,
    createdAt: new Date('2024-01-01T00:00:00Z'),
    party_type: 'person',
    roles: ['owner'],
    name: 'Paul Logan',
    profession: 'Thoroughbred Owner',
    started_year: 2012,
    country_of_birth: 'Australia',
  },
  {
    id: P_JOCKEY_TD,
    createdAt: new Date('2024-01-01T00:00:00Z'),
    party_type: 'person',
    roles: ['jockey'],
    name: 'Tim Donnelly',
    profession: 'Jockey',
    started_year: 2016,
    country_of_birth: 'Australia',
  },
  {
    id: P_JOCKEY_BH,
    createdAt: new Date('2024-01-01T00:00:00Z'),
    party_type: 'person',
    roles: ['jockey'],
    name: 'Blake Hunter',
    profession: 'Jockey',
    started_year: 2014,
    country_of_birth: 'Australia',
  },
  {
    id: P_JOCKEY_RC,
    createdAt: new Date('2024-01-01T00:00:00Z'),
    party_type: 'person',
    roles: ['jockey'],
    name: 'Rachel Cross',
    profession: 'Jockey',
    started_year: 2018,
    country_of_birth: 'Australia',
  },
  {
    id: P_BREEDER_KS,
    createdAt: new Date('2024-01-01T00:00:00Z'),
    party_type: 'organisation',
    roles: ['breeder'],
    name: 'Kingston Stud',
    profession: 'Thoroughbred Stud Farm',
    base_location: 'Bairnsdale, VIC',
  },
  {
    id: P_BREEDER_WP,
    createdAt: new Date('2024-01-01T00:00:00Z'),
    party_type: 'organisation',
    roles: ['breeder'],
    name: 'Windrush Park',
    profession: 'Thoroughbred Stud Farm',
    base_location: 'Coolac, NSW',
  },
  {
    id: P_BREEDER_EP,
    createdAt: new Date('2024-01-01T00:00:00Z'),
    party_type: 'organisation',
    roles: ['breeder'],
    name: 'Eastern Plains Thoroughbreds',
    profession: 'Thoroughbred Stud Farm',
    base_location: 'Bathurst, NSW',
  },
];

// ─── Additional Horses ────────────────────────────────────────────────────────
const NORTHERN_STAR: Horse = {
  id: 'seed-northern-star-001',
  createdAt: new Date('2024-02-01T00:00:00Z'),
  name: 'Northern Star',
  sex: 'Colt',
  dob: '2021-10-14',
  colour: 'Bay',
  country: 'Australia',
  sire: 'STAR WITNESS (AUS)',
  sireSire: 'STARCRAFT (NZ)',
  sireDam: 'BLINK OF AN EYE (AUS)',
  dam: 'NORTHERN LIGHTS (IRE)',
  damYob: 2012,
  damSire: 'GALILEO (IRE)',
  damDam: 'AURORA BOREALIS (IRE)',
  trainerIds: [P_TRAINER_RH],
  ownerIds: [P_OWNER_SS],
  jockeyIds: [P_JOCKEY_JMC],
  breederIds: [P_BREEDER_NS],
  careerRecord: '5:4-0-1',
  careerWinnings: 312000,
  lastTenForm: '1-1-3-1-1',
  seasonRecord: '3:3-0-0',
  currentRating: 105,
  pedigreeNotes:
    'Northern Star is bred for speed and stamina in equal measure. By the multiple Group 1 winning miler Star Witness and out of a Galileo mare, this colt carries European class in his dam line with the raw speed of his Australian sire. The combination is rare and compelling.',
  pullQuote: 'The kind of horse you see once a decade — once he learns to relax, the sky is the limit.',
  imageUrl: 'https://images.pexels.com/photos/635499/pexels-photo-635499.jpeg',
};

const DESERT_QUEEN: Horse = {
  id: 'seed-desert-queen-001',
  createdAt: new Date('2024-03-01T00:00:00Z'),
  name: 'Desert Queen',
  sex: 'Mare',
  dob: '2020-09-22',
  colour: 'Chestnut',
  country: 'Australia',
  sire: 'DISSIDENT (AUS)',
  sireSire: 'EXCEED AND EXCEL (AUS)',
  sireDam: "DISSIDENT'S DREAM (AUS)",
  dam: 'QUEEN OF SAND (IRE)',
  damYob: 2014,
  damSire: 'INVINCIBLE SPIRIT (IRE)',
  damDam: 'SANDY QUEEN (IRE)',
  trainerIds: [P_TRAINER_OJ],
  ownerIds: [P_OWNER_KD],
  jockeyIds: [P_JOCKEY_MR],
  breederIds: [P_BREEDER_SF],
  careerRecord: '9:6-1-1',
  careerWinnings: 784000,
  lastTenForm: '1-1-2-1-1-1-3-1',
  seasonRecord: '4:3-1-0',
  currentRating: 118,
  pedigreeNotes:
    'Desert Queen is a daughter of the brilliant but tragically short-lived Dissident, whose sire Exceed and Excel stamped him with exceptional turn of foot. Her dam Queen of Sand by Invincible Spirit brings European class and a natural aptitude for firm summer tracks. The result is one of the most complete mares seen in Australian racing in recent memory.',
  pullQuote: 'She does not know she is a mare racing against colts — and that fearlessness is precisely her greatest weapon.',
  imageUrl: 'https://images.pexels.com/photos/1571939/pexels-photo-1571939.jpeg',
};

const IRON_MONARCH: Horse = {
  id: 'seed-iron-monarch-001',
  createdAt: new Date('2024-04-01T00:00:00Z'),
  name: 'Iron Monarch',
  sex: 'Gelding',
  dob: '2018-11-02',
  colour: 'Dark Bay',
  country: 'Australia',
  sire: 'LONHRO (AUS)',
  sireSire: 'OCTAGONAL (NZ)',
  sireDam: "SHANTHA'S CHOICE (AUS)",
  dam: 'IRON DUCHESS (AUS)',
  damYob: 2010,
  damSire: 'DANEHILL DANCER (IRE)',
  damDam: 'GOLDEN DUCHESS (AUS)',
  trainerIds: [P_TRAINER_CW],
  ownerIds: [P_OWNER_RM],
  jockeyIds: [P_JOCKEY_CWJ],
  breederIds: [P_BREEDER_NS],
  careerRecord: '24:8-5-4',
  careerWinnings: 1240000,
  lastTenForm: '1-3-2-1-4-1-2-1-3-1',
  seasonRecord: '4:2-1-0',
  currentRating: 108,
  pedigreeNotes:
    "Iron Monarch is a son of the legendary Lonhro — one of Australia's most successful sires. His dam Iron Duchess by Danehill Dancer adds European flair and a remarkable engine. This gelding has taken time to mature but has returned to his best form this preparation with two dominant front-running performances in night racing at Moonee Valley.",
  pullQuote: 'He is the engine room of any race he enters — not brilliant, but relentlessly brave.',
  imageUrl: 'https://images.pexels.com/photos/1995842/pexels-photo-1995842.jpeg',
};

const SILVER_DART: Horse = {
  id: 'seed-silver-dart-001',
  createdAt: new Date('2024-05-01T00:00:00Z'),
  name: 'Silver Dart',
  sex: 'Filly',
  dob: '2022-08-05',
  colour: 'Grey',
  country: 'Australia',
  sire: 'SO YOU THINK (NZ)',
  sireSire: 'HIGH CHAPARRAL (IRE)',
  sireDam: 'TRIASSIC (AUS)',
  dam: 'SILVER LINING (AUS)',
  damYob: 2015,
  damSire: 'FASTNET ROCK (AUS)',
  damDam: 'CLOUD BURST (AUS)',
  trainerIds: [P_TRAINER_SW],
  ownerIds: [P_OWNER_BF],
  jockeyIds: [P_JOCKEY_TD],
  breederIds: [P_BREEDER_KS],
  careerRecord: '3:2-1-0',
  careerWinnings: 98000,
  lastTenForm: '2-1-1',
  seasonRecord: '3:2-1-0',
  currentRating: 87,
  pedigreeNotes:
    'Silver Dart is a daughter of the outstanding So You Think, whose High Chaparral influence consistently produces high-class middle-distance horses. Her dam Silver Lining by Fastnet Rock is a full sister to a Group 2 winner in France, giving Silver Dart an unusual combination of speed and potential for improvement as she stretches to further ground this spring.',
  pullQuote: 'She floats over the ground like she was born to do this. A filly with a very bright future.',
  imageUrl: 'https://images.pexels.com/photos/12995066/pexels-photo-12995066.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
};

const STORM_RAIDER: Horse = {
  id: 'seed-storm-raider-001',
  createdAt: new Date('2024-06-01T00:00:00Z'),
  name: 'Storm Raider',
  sex: 'Colt',
  dob: '2021-11-18',
  colour: 'Dark Bay',
  country: 'Australia',
  sire: 'MEDAGLIA D\'ORO (USA)',
  sireSire: 'EL PRADO (IRE)',
  sireDam: 'CAPPUCINO BAY (USA)',
  dam: 'STORM CLOUD (AUS)',
  damYob: 2013,
  damSire: 'REDOUTE\'S CHOICE (AUS)',
  damDam: 'WHISPER CREEK (AUS)',
  trainerIds: [P_TRAINER_ML],
  ownerIds: [P_OWNER_GC],
  jockeyIds: [P_JOCKEY_BH],
  breederIds: [P_BREEDER_WP],
  careerRecord: '6:3-2-0',
  careerWinnings: 187000,
  lastTenForm: '1-2-1-2-3-1',
  seasonRecord: '3:2-0-0',
  currentRating: 96,
  pedigreeNotes:
    "Storm Raider carries the American influence of Medaglia d'Oro — a sire renowned for producing precocious juveniles that train on to be top-class three-year-olds. His dam Storm Cloud by the legendary Redoute's Choice was a talented winner herself over 1400m. The cross is textbook modern Australian breeding, built for speed with a solid ceiling of staying ability.",
  pullQuote: 'You can see the American blood in him — all class and heart when it really matters.',
  imageUrl: 'https://images.pexels.com/photos/2123375/pexels-photo-2123375.jpeg',
};

const VELVET_HAMMER: Horse = {
  id: 'seed-velvet-hammer-001',
  createdAt: new Date('2024-07-01T00:00:00Z'),
  name: 'Velvet Hammer',
  sex: 'Mare',
  dob: '2019-09-30',
  colour: 'Bay',
  country: 'Australia',
  sire: 'I AM INVINCIBLE (AUS)',
  sireSire: 'INVINCIBLE SPIRIT (IRE)',
  sireDam: 'CANTICLE (AUS)',
  dam: 'VELVET TOUCH (AUS)',
  damYob: 2011,
  damSire: 'REDOUTE\'S CHOICE (AUS)',
  damDam: 'SOFT LANDING (AUS)',
  trainerIds: [P_TRAINER_TH],
  ownerIds: [P_OWNER_PL],
  jockeyIds: [P_JOCKEY_RC],
  breederIds: [P_BREEDER_EP],
  careerRecord: '14:5-3-2',
  careerWinnings: 468000,
  lastTenForm: '1-3-2-1-1-4-2-1',
  seasonRecord: '4:2-1-1',
  currentRating: 101,
  pedigreeNotes:
    "Velvet Hammer is a daughter of the champion sprinting sire I Am Invincible, one of the most consistent producers of Group 1 horses in Australia. Her dam Velvet Touch is a daughter of Redoute's Choice, and this combination has produced a versatile mare who is equally at home over the sprint distances and up to 1600m. She handles all tracks and conditions.",
  pullQuote: "She is the quiet professional of the yard — goes about her work without fuss and delivers every time.",
  imageUrl: 'https://images.pexels.com/photos/1639729/pexels-photo-1639729.jpeg',
};

const PACIFIC_MONARCH: Horse = {
  id: 'seed-pacific-monarch-001',
  createdAt: new Date('2024-08-01T00:00:00Z'),
  name: 'Pacific Monarch',
  sex: 'Gelding',
  dob: '2017-10-12',
  colour: 'Bay',
  country: 'Australia',
  sire: 'SAVABEEL (AUS)',
  sireSire: 'ZABEEL (NZ)',
  sireDam: 'WHERE YOU ARE (NZ)',
  dam: 'PACIFIC OCEAN (AUS)',
  damYob: 2009,
  damSire: 'ENCOSTA DE LAGO (AUS)',
  damDam: 'CORAL COAST (AUS)',
  trainerIds: [P_TRAINER_RH],
  ownerIds: [P_OWNER_SS],
  jockeyIds: [P_JOCKEY_JMC],
  breederIds: [P_BREEDER_NS],
  careerRecord: '31:10-7-5',
  careerWinnings: 1780000,
  lastTenForm: '2-1-3-1-4-1-2-3-1-2',
  seasonRecord: '4:1-2-0',
  currentRating: 114,
  pedigreeNotes:
    "Pacific Monarch is a seven-year-old gelding that has been one of the most consistent performers in the country for four seasons. By Savabeel — New Zealand's champion sire — and out of an Encosta de Lago mare, he has the classic Australasian staying pedigree that rewards patience. He is at his absolute best over 2400m on a good to firm track at Flemington.",
  pullQuote: "Seven years old and still improving — Pacific Monarch is the model of equine professionalism.",
  imageUrl: 'https://images.pexels.com/photos/1128428/pexels-photo-1128428.jpeg',
};

const WILD_HORIZON: Horse = {
  id: 'seed-wild-horizon-001',
  createdAt: new Date('2024-09-01T00:00:00Z'),
  name: 'Wild Horizon',
  sex: 'Colt',
  dob: '2022-10-03',
  colour: 'Chestnut',
  country: 'Australia',
  sire: 'WRITTEN TYCOON (AUS)',
  sireSire: 'IGLESIA (AUS)',
  sireDam: 'TYCOON TARA (AUS)',
  dam: 'WILD SPIRIT (AUS)',
  damYob: 2016,
  damSire: 'SNITZEL (AUS)',
  damDam: 'SPIRIT OF SONG (AUS)',
  trainerIds: [P_TRAINER_OJ],
  ownerIds: [P_OWNER_KD],
  jockeyIds: [P_JOCKEY_MR],
  breederIds: [P_BREEDER_SF],
  careerRecord: '2:2-0-0',
  careerWinnings: 46000,
  lastTenForm: '1-1',
  seasonRecord: '2:2-0-0',
  currentRating: 78,
  pedigreeNotes:
    "Wild Horizon is an unbeaten two-year-old colt whose career is just beginning. By Written Tycoon — the dominant sprint sire in Australia — and out of a Snitzel mare, he is bred at the apex of Australian speed. Two dominant barrier trial wins and a perfect record on debut and second-up suggest he is one of the more exciting juveniles to watch this spring carnival.",
  pullQuote: "Still learning, still growing — but the talent is obvious. He could be anything.",
  imageUrl: 'https://images.pexels.com/photos/3280908/pexels-photo-3280908.jpeg',
};

const GOLDEN_BAY: Horse = {
  id: 'seed-golden-bay-001',
  createdAt: new Date('2024-10-01T00:00:00Z'),
  name: 'Golden Bay',
  sex: 'Mare',
  dob: '2018-08-22',
  colour: 'Golden Chestnut',
  country: 'New Zealand',
  sire: 'OCEAN PARK (NZ)',
  sireSire: 'THORN PARK (AUS)',
  sireDam: 'OCEAN VALE (NZ)',
  dam: 'GOLDEN COAST (NZ)',
  damYob: 2010,
  damSire: 'GENEROUS (IRE)',
  damDam: 'GOLDEN CLOUD (NZ)',
  trainerIds: [P_TRAINER_SW],
  ownerIds: [P_OWNER_BF],
  jockeyIds: [P_JOCKEY_CWJ],
  breederIds: [P_BREEDER_KS],
  careerRecord: '18:7-4-3',
  careerWinnings: 892000,
  lastTenForm: '1-2-1-3-1-4-2-1',
  seasonRecord: '5:3-1-1',
  currentRating: 109,
  pedigreeNotes:
    "Golden Bay is a New Zealand-bred mare who has made her home in Australian racing with outstanding results. By Ocean Park — the champion New Zealand sire — and out of a Generous mare, she brings genuine European-class stamina in her pedigree. She is equally effective at Flemington and Royal Randwick, and consistently produces her best form when the track is rated Good 4.",
  pullQuote: "New Zealand bred but Melbourne hearted — Golden Bay runs like she owns every straight she enters.",
  imageUrl: 'https://images.pexels.com/photos/27305774/pexels-photo-27305774.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
};

// ─── Exports ──────────────────────────────────────────────────────────────────
export { SAVILE_ROW_ID };

export const SEED_HORSES: Horse[] = [
  SAVILE_ROW,
  NORTHERN_STAR,
  DESERT_QUEEN,
  IRON_MONARCH,
  SILVER_DART,
  STORM_RAIDER,
  VELVET_HAMMER,
  PACIFIC_MONARCH,
  WILD_HORIZON,
  GOLDEN_BAY,
];

export const SEED_PARTIES_ALL: Party[] = [
  ...SEED_PARTIES,
  ...EXTRA_PARTIES,
];
